#+TITLE: GnuPG - Software
#+STARTUP: showall
#+SETUPFILE: "../share/setup.inc"

* GnuPG --- The Universal Crypto Engine

  GnuPG is a command line tool without any graphical user interface.
  It is an universal crypto engine which can be used directly from a
  command line prompt, from shell scripts, or from other programs.
  Therefore GnuPG is often used as the actual crypto backend of other
  applications.

  Even when used on the command line it provides all functionality
  needed - this includes an interactive menu system.  The set of
  commands of this tool will always be a superset of those provided by
  any frontends.

  - Full OpenPGP implementation (see RFC4880 at [[http://www.rfc-editor.org/][RFC Editor]]).
  - Full CMS/X.509 (S/MIME) implementation.
  - Ssh-agent implementation
  - Runs on all Unix platforms, Windows and macOS.
  - A full replacement of PGP; written from scratch.
  - Does not use any patented algorithms.
  - Freely available under the GPL;
  - Can be used as a filter program.
  - Better functionality than PGP with state of the art security features.
  - Decrypts and verifies PGP 5, 6 and 7 messages.
  - Supports RSA, ECDH, ECDSA, EdDSA, Elgamal, DSA, AES, Camellia,
    3DES, Twofish, SHA2, and many more algorithms.
  - Language support for a load of languages.
  - Online help system.
  - Optional anonymous message receivers.
  - Integrated support for HKP keyservers (sks-keyservers.net).
  - and many more things....


* Related Software

  Over the years, GnuPG has widly gained in popularity to become the
  standard /de-facto/ as free software for private communication and
  digital signature. As such, it is by no mean surprisingly to find
  out that there are so many programms orbiting around GnuPG.

  For your convenience, GnuPG-related software has been grouped here in
  three big categories. If you are working for a new project and want to
  be listed here, please, feel free to contact the [[mailto:webmaster@gnupg.org][webmaster]] .

  Please note that, being part of the [[http://www.gnu.org/][GNU Project]], we can not link to
  any project which can not be labeled as [[http://www.gnu.org/philosophy/free-sw.html][free software]] . If you found
  a link on these pages to a project which does not fulfill this
  requirement (a good checkpoint is the [[https://directory.fsf.org/][ FSF/UNESCO Free Software
  Directory]]) please let us know by contacting the [[mailto:webmaster@gnupg.org][webmaster]] .

  -  [[file:frontends.org][Frontends]] :: This category collects together all the software for
                  various platforms which relays on GnuPG command line
                  and provides some sort of easy-to-use user
                  interface.
  -  [[file:tools.org][Tools]] :: Under this link you'll find tools mostly used to manage
              GnuPG keys.
  -  [[file:libraries.org][Libraries]] :: This page hosts projects which aim is to build an
                  abstraction layer for who wants to painlessly add
                  GnuPG capabilities to their software.
  -  [[file:swlist.org][All]] :: Direct access to all descriptions.
