#+TITLE: GnuPG - Frontends
#+STARTUP: showall
#+SETUPFILE: "../share/setup.inc"

* Frontends

  Here it is some lists of software with support for GnuPG.

  For your convenience, frontends have been grouped together into
  homogeneous categories. A frontend may belong to one or more
  categories at a time. A list is sorted in an alphabetical order.

  -  [[#gui][GUI frontends]]
  -  [[#mua][MUA frontends]]
  -  [[#chat][chat programs]]
  -  [[#net][network related]]
  -  [[#scr][frontends for scripting]]
  -  [[#nix][for *nix platform]]
  -  [[#win][for Windows platform]]
  -  [[#mac][for Mac platform]]

  If you feel wanting to improve these lists, please, fill in a
  [[#gpgweb][Problem Report]] form.

** GUI Frontends

   -  [[http://code.google.com/p/cryptophane/][Cryptophane]] :: Cryptophane is an easy-to-use application for MS
                     Windows. It allows users to encrypt, sign,
                     decrypt, and perform key maintenance without
                     having to deal with GnuPG's command-line
                     interface.
   -  [[http://www.gajim.org/][Gajim]] :: The goal of Gajim is to provide a full featured and
               easy to use Jabber client. Gajim works nicely with
               GNOME, but does not require it to run. It is released
               under the GNU General Public License.
   -  [[http://www.tech-faq.com/gnupg-shell.shtml][GnuPG Shell]] :: GnuPG Shell is a cross-platform graphical
                     frontend for GnuPG.
   -  [[file:gpa/index.org][GPA]] :: Aims to be the standard GnuPG graphical frontend. [[gpa/index.en.html][GPA]] is
             hosted on this site.
   -  [[http://devel-home.kde.org/~kgpg/][KGpg]] :: Is a KDE frontend for GnuPG.
   -  [[http://seahorse.sf.net/][Seahorse]] :: Is a GNOME frontend for GnuPG.
   -  [[http://www.media-art-online.org/wija/][wija]] :: wija is a free and cross-platform Jabber/XMPP client
              written in Java, with built-in GnuPG key rings
              management GUI. Its extended protocols allow users to
              encrypt chat and multi-user chat as well as
              encrypting/signing messages and signing presence of the
              user. It is multilingual and runs on GNU/Linux, Mac OS X
              and Windows.
   -  [[http://freshmeat.net/projects/xap/][XAP]] :: Is the X application panel and filemanager.


** MUA Frontends

   -  [[http://www.claws-mail.org/][Claws Mail]] :: Is a very nice GTK+ based MUA with full support
                    for GnuPG. The Windows version is part of [[http://www.gpg4win.org/][Gpg4win]]
                    .
   -  [[http://www.enigmail.net/][Enigmail]] :: Is a plug-in for Mozilla's mailer.
   -  [[http://www.adobner.de/eudoragpg/][EudoraGPG]] :: Is a plugin for the proprietary Eudora MUA.
   -  [[http://www.ximian.com/products/ximian_evolution][Evolution]] :: Is a catch all MUA application for the GNOME
                   desktop.
   -  [[http://www.beedub.com/exmh/][exmh]] :: Is a Tcl/Tk based MUA.
   -  [[http://business-php.com/opensource/ez-pine-gpg/][ez-pine-gpg]] :: Is a set of scripts that allows beginners and
                     experts to use gpg with Pine. There are plenty of
                     other applications that allow gpg to be used with
                     Pine: this one is intended to be the best, since
                     it merges intuitive use with powerful
                     features. The result is an application that's not
                     only fast and secure, but also perfect for
                     novices and power-users alike.
   -  [[http://www.gnu.org/software/anubis/][GNU Anubis]] :: Is an outgoing mail processor, and an SMTP tunnel
                    between the MUA and the MTA. It strongly uses the
                    GnuPG via the GPGME interface. With this GNU tool
                    you can encrypt or sign an outgoing mail
                    on-the-fly.
   -  [[http://www.collaboration-world.com/gnumail/][GNUmail.app]] :: Is a GNUStep MUA which now has support for GnuPG.
   -  [[http://linux.oregpreshaz.hu/script.html][gpg\_mail]] :: This script is able to encode/sign emails in an
                   automatic fashion. There is also a [[http://linux.choma.hu/gpg-script/][mirror site]]
                   available.
   -  [[http://wald.intevation.org/projects/gpgoe][GPGOE]] :: Is a plugin for the proprietary Outlook Express MUA.
   -  [[http://www.g10code.de/p-gpgol.html][GPGol]] :: A plug-in for Microsoft Outlook 2003.
   -  [[http://sites.inka.de/tesla/gpgrelay.html][GPGrelay]] :: Is a Windows program which can be used to use GnuPG
                  with all MUAs.
   -  [[http://kmail.kde.org/][KMail]] :: From the KDE desktop, it does also support GnuPG.
   -  [[http://www.snafu.priv.at/kuvert.html][kuvert]] :: This frontend is for GnuPG and old-style pgp2. It
                works slightly similar to Raph Levien's premail: it
                sits between MUA and MTA and decides based on the
                keyring contents whether to sign, sign/encrypt or
                leave an email as it is.  kuvert is unix-only and
                designed to work for outbound emails only.  It's a
                daemon tool and requires some form of passphrase
                cache.  kuvert has been around (under earlier names)
                since about 1996.
   -  [[http://www.physto.se/~p99jlu/MagicPGP.html][MagicPGP]] :: Is yet another set of scripts to use GnuPG with
                  Pine.
   -  [[http://www.pobox.com/~lbudney/linux/software/mailcrypt.html][Mailcrypt]] :: For Emacs. You may need the latest [[http://www.lothar.com/tech/crypto/][patches]] until
                   there is a new release of Mailcrypt.
   -  [[http://www.mew.org/][Mew]] :: Has support for GnuPG.
   -  [[http://www.mutt.org/][Mutt]] :: Is an advanced MUA with complete MIME and GnuPG/PGP
              support. It is also available an
              [[ftp://ftp.guug.de/pub/mutt/][internationalized version]] .
   -  [[https://yourmom.dhs.org/pgp/][OpenPGP Webmail]] :: Is a web based mailer to send encrypted
        messages.
   -  [[#fend_mua-PGG][PGG]] :: PGG is a complete PGP signing/encrypting solution
             provided from scratch by the Gnus development team. It
             deserves the same than [[#fend_mua-Mailcrypt][mailcrypt]] but it has also native
             MIME support whereas mailcrypt does not. There is no PGG
             homepage at the moment, sorry.
   -  [[http://pgpenvelope.sourceforge.net/][pgpenvelope]] :: Is a Pine and procmail filter which allows one to
                     process messages with GnuPG.
   -  [[http://www.netspace.net.au/~ggt/privtool.html][privtool]] :: Sorry, no description available.
   -  [[http://www.memecode.com/scribe.php][Scribe]] :: Scribe is a small and fast email client that lets you
                send, receive and manage email without fuss. Scribe
                comes with a [[http://www.memecode.com/scribe/gnupg.php][plugin]] that calls GnuPG.
   -  [[http://www.sys3175.co.uk/securemail.php][Securemail]] :: Is another webmail client.
   -  [[http://www.squirrelmail.org/plugin_view.php?id=153][Squirrelmail Plugin]] :: A gpg plugin for the popular [[http://www.squirrelmail.org/][Squirrelmail]]
        web mail server.
   -  [[http://sylpheed.sraoss.jp/en/][Sylpheed]] :: Is a very nice GTK+ based MUA with full support for
                  GnuPG.
   -  [[http://www.lothlann.freeserve.co.uk/pjb/topal/][Topal]] :: Is another program to use GnuPG with Pine.
   -  [[http://xfmail.slappy.org/][XFmail]] :: Works with GnuPG.


** Chat programs

   -  [[http://gabber.sourceforge.net/][Gabber]] :: Gabber is a Free and Open Source GNOME client for an
                instant messaging system called Jabber. Jabber is a
                Free and Open Source distributed instant messaging
                system. It does not rely on a single server, and the
                protocol is well documented. Jabber allows
                communication with many different instant messaging
                systems, including ICQ and AIM.
   -  [[http://www.gajim.org/][Gajim]] :: The goal of Gajim is to provide a full featured and
               easy to use Jabber client. Gajim works nicely with
               GNOME, but does not require it to run. It is released
               under the GNU General Public License.
   -  [[http://miranda-icq.sourceforge.net/][Miranda ICQ]] :: Has support for GnuPG.
   -  [[http://psi.affinix.com/][PSI]] :: Psi is a free and crossplatform client for connecting to
             the Jabber network. It supports multiple accounts, group
             chat, Unicode, and strong security (TLS and GnuPG).
   -  [[http://tkabber.jabber.ru/][Tkabber]] :: Tkabber is a free client for an instant messaging
                 system called Jabber. It is written in Tcl/Tk and
                 supports many features like support of unicode, ssl
                 support, http proxy, file transfers and support of
                 multi-user conference protocol.
   -  [[http://www.media-art-online.org/wija/][wija]] :: wija is a free and cross-platform Jabber/XMPP client
              written in Java, with built-in GnuPG key rings
              management GUI. Its extended protocols allow users to
              encrypt chat and multi-user chat as well as
              encrypting/signing messages and signing presence of the
              user. It is multilingual and runs on GNU/Linux, Mac OS X
              and Windows.

** Network Related

   -  [[http://www.freenigma.org/][freenigma]] :: Is a server based solution for centralized and
                   transparent encryption and signatures.  It comes
                   with a web admin interface and may either be used
                   as a drop in MTA replacement or as an additional
                   MTA.
   -  [[http://www.freenigma.com/][freenigma]] :: freenigma is an OpenPGP web service for easy key
                   management. It allows encryption without taking
                   care of keys. A documented API is available as well
                   as several tools to access this web service.
   -  [[http://eepatents.com/privaria/][Privaria]] :: Is a secure networking suite that uses GnuPG as part
                  of its authentication and encryption scheme.

** Frontends for scripting

   -  [[http://business-php.com/opensource/gpg_encrypt/][gpg\_encrypt()]] :: gpg\_encrypt() is a PHP function that will
        allow you to easily use GnuPG to encrypt data to your public
        PGP key and mail that encrypted data to yourself, where it can
        be securely decrypted with your private key. This is designed
        primarily for use with web-based forms but can be used to
        encrypt any data.
   -  [[http://linux.oregpreshaz.hu/script.html][gpg\_mail]] :: This script is able to encode/sign emails in an
                   automatic fashion. There is also a [[http://linux.choma.hu/gpg-script/][mirror site]]
                   available.
   -  [[http://www.physto.se/~p99jlu/MagicPGP.html][MagicPGP]] :: Is yet another set of scripts to use GnuPG with
                  Pine.
   -  [[http://www.bell-labs.com/projects/nsbd/][NSBD]] :: The Not-So-Bad Distribution system.
   -  [[http://pgpenvelope.sourceforge.net/][pgpenvelope]] :: Is a Pine and procmail filter which allows one to
                     process messages with GnuPG.
   -  [[http://www.nessie.de/mroth/pgpgpg/][pgpgpg]] :: Is a comandline wrapper tool to allow the use of
                scripts written for PGP with GnuPG.
   -  [[http://www.sanface.com/pgphtml.html][PGPHTML]] :: Is a perl script to sign HTML pages.
   -  [[http://py-gnupg.sourceforge.net/][Python GnuPGInterface]] :: Is what the name says.
   -  [[http://soupermail.sourceforge.net/][Soupermail]] :: Is a versatile HTML form handler.


** For Unix

   -  [[http://www.claws-mail.org/][Claws Mail]] :: Is a very nice GTK+ based MUA with full support
                    for GnuPG. The Windows version is part of [[http://www.gpg4win.org/][Gpg4win]]
                    .
   -  [[http://www.enigmail.net/][Enigmail]] :: Is a plug-in for Mozilla's mailer.
   -  [[http://www.ximian.com/products/ximian_evolution][Evolution]] :: Is a catch all MUA application for the GNOME
                   desktop.
   -  [[http://www.beedub.com/exmh/][exmh]] :: Is a Tcl/Tk based MUA.
   -  [[http://business-php.com/opensource/ez-pine-gpg/][ez-pine-gpg]] :: ez-pine-gpg is a set of scripts that allows
                     beginners and experts to use gpg with Pine. There
                     are plenty of other applications that allow gpg
                     to be used with Pine: this one is intended to be
                     the best, since it merges intuitive use with
                     powerful features. The result is an application
                     that's not only fast and secure, but also perfect
                     for novices and power-users alike.
   -  [[http://gabber.sourceforge.net/][Gabber]] :: Gabber is a Free and Open Source GNOME client for an
                instant messaging system called Jabber. Jabber is a
                Free and Open Source distributed instant messaging
                system. It does not rely on a single server, and the
                protocol is well documented. Jabber allows
                communication with many different instant messaging
                systems, including ICQ and AIM.
   -  [[http://www.tech-faq.com/gnupg-shell.shtml][GnuPG Shell]] :: GnuPG Shell is a cross-platform graphical
                     frontend for GnuPG.
   -  [[gpa/index.en.html][GPA]] :: Aims to be the standard GnuPG graphical frontend. [[gpa/index.en.html][GPA]] is
             hosted on this site.
   -  [[http://linux.oregpreshaz.hu/script.html][gpg\_mail]] :: This script is able to encode/sign emails in an
                   automatic fashion. There is also a [[http://linux.choma.hu/gpg-script/][mirror site]]
                   available.
   -  [[http://devel-home.kde.org/~kgpg/][KGpg]] :: Is a KDE frontend for GnuPG.
   -  [[http://kmail.kde.org/][KMail]] :: From the KDE desktop, it does also support GnuPG.
   -  [[http://www.snafu.priv.at/kuvert.html][kuvert]] :: This frontend is for GnuPG and old-style pgp2. It
                works slightly similar to Raph Levien's premail: it
                sits between MUA and MTA and decides based on the
                keyring contents whether to sign, sign/encrypt or
                leave an email as it is.  kuvert is unix-only and
                designed to work for outbound emails only.  It's a
                daemon tool and requires some form of passphrase
                cache.  kuvert has been around (under earlier names)
                since about 1996.
   -  [[http://www.physto.se/~p99jlu/MagicPGP.html][MagicPGP]] :: Is yet another set of scripts to use GnuPG with
                  Pine.
   -  [[http://www.pobox.com/~lbudney/linux/software/mailcrypt.html][Mailcrypt]] :: For Emacs. You may need the latest [[http://www.lothar.com/tech/crypto/][patches]] until
                   there is a new release of Mailcrypt.
   -  [[http://www.mew.org/][Mew]] :: Has support for GnuPG.
   -  [[http://www.mutt.org/][Mutt]] :: Is an advanced MUA with complete MIME and GnuPG/PGP
              support. It is also available
              an [[ftp://ftp.guug.de/pub/mutt/][internationalized version]].
   -  [[#fend_nix-PGG][PGG]] :: PGG is a complete PGP signing/encrypting solution
             provided from scratch by the Gnus development team. It
             deserves the same than [[#fend_mua-Mailcrypt][mailcrypt]] but it has also native
             MIME support whereas mailcrypt does not. There is no PGG
             homepage at the moment, sorry.
   -  [[http://pgpenvelope.sourceforge.net/][pgpenvelope]] :: Is a Pine and procmail filter which allows one to
                     process messages with GnuPG.
   -  [[http://www.nessie.de/mroth/pgpgpg/][pgpgpg]] :: Is a comandline wrapper tool to allow the use of
                scripts written for PGP with GnuPG.
   -  [[http://psi.affinix.com/][PSI]] :: Psi is a free and crossplatform client for connecting to
             the Jabber network. It supports multiple accounts, group
             chat, Unicode, and strong security (TLS and GnuPG).
   -  [[http://www.memecode.com/scribe.php][Scribe]] :: Scribe is a small and fast email client that lets you
                send, receive and manage email without fuss. Scribe
                comes with a [[http://www.memecode.com/scribe/gnupg.php][plugin]] that calls GnuPG.
   -  [[http://seahorse.sf.net/][Seahorse]] :: Is a GNOME frontend for GnuPG.
   -  [[http://sylpheed.sraoss.jp/en/][Sylpheed]] :: Is a very nice GTK+ based MUA with full support for
                  GnuPG.
   -  [[http://tkabber.jabber.ru/][Tkabber]] :: Tkabber is a free client for an instant messaging
                 system called Jabber. It is written in Tcl/Tk and
                 supports many features like support of unicode, ssl
                 support, http proxy, file transfers and support of
                 multi-user conference protocol.
   -  [[http://www.lothlann.freeserve.co.uk/pjb/topal/][Topal]] :: Is another program to use GnuPG with Pine.
   -  [[http://www.media-art-online.org/wija/][wija]] :: wija is a free and cross-platform Jabber/XMPP client
              written in Java, with built-in GnuPG key rings
              management GUI. Its extended protocols allow users to
              encrypt chat and multi-user chat as well as
              encrypting/signing messages and signing presence of the
              user. It is multilingual and runs on GNU/Linux, Mac OS X
              and Windows.
   -  [[http://freshmeat.net/projects/xap/][XAP]] :: Is the X application panel and filemanager.


** For Windows

   -  [[http://www.claws-mail.org/][Claws Mail]] :: Is a very nice GTK+ based MUA with full support
                    for GnuPG. The Windows version is part of [[http://www.gpg4win.org/][Gpg4win]].
   -  [[http://code.google.com/p/cryptophane/][Cryptophane]] :: Cryptophane is an easy-to-use application for MS
                     Windows. It allows users to encrypt, sign,
                     decrypt, and perform key maintenance without
                     having to deal with GnuPG's command-line
                     interface.
   -  [[http://www.enigmail.net/][Enigmail]] :: Is a plug-in for Mozilla's mailer.
   -  [[http://www.adobner.de/eudoragpg/][EudoraGPG]] :: Is a plugin for the proprietary Eudora MUA.
   -  [[http://www.gpg4win.org/][Gpg4win]] :: Gpg4win is an installer package for Windows with
                 computer programs and handbooks for email and file
                 encryption.
   -  [[http://wald.intevation.org/projects/gpgoe][GPGOE]] :: Is a plugin for the proprietary Outlook Express MUA.
   -  [[http://www.g10code.de/p-gpgol.html][GPGol]] :: A plug-in for Microsoft Outlook 2003.
   -  [[http://sites.inka.de/tesla/gpgrelay.html][GPGrelay]] :: Is a Windows program which can be used to use GnuPG
                  with all MUAs.
   -  [[http://www.memecode.com/scribe.php][Scribe]] :: Scribe is a small and fast email client that lets you
                send, receive and manage email without fuss. Scribe
                comes with a [[http://www.memecode.com/scribe/gnupg.php][plugin]] that calls GnuPG.
   -  [[http://www.media-art-online.org/wija/][wija]] :: wija is a free and cross-platform Jabber/XMPP client
              written in Java, with built-in GnuPG key rings
              management GUI. Its extended protocols allow users to
              encrypt chat and multi-user chat as well as
              encrypting/signing messages and signing presence of the
              user. It is multilingual and runs on GNU/Linux, Mac OS X
              and Windows.

** For Mac

   -  [[http://www.enigmail.net/][Enigmail]] :: Is a plug-in for Mozilla's mailer.
   -  [[http://www.gpgtools.org/gpgmail.html][GPGMail]] :: Is a MUA for MAC OS X.
   -  [[http://gpgtools.org/][GPGTools]] :: GPGTools is an installer package for Mac OS X. It
                  integrates all required modules for easy use of
                  GnuPG on this OS.
   -  [[http://www.gpgtools.org/macgpg1.html][MacGPG]] :: The MacGPG project has information on using GnuPG on
                OS-X.
   -  [[http://www.gpgtools.org/macgpg2.html][MacGPG2]] :: The MacGPG2 project has information on using GnuPG-2
                 on OS-X.
   -  [[http://www.media-art-online.org/wija/][wija]] :: wija is a free and cross-platform Jabber/XMPP client
              written in Java, with built-in GnuPG key rings
              management GUI. Its extended protocols allow users to
              encrypt chat and multi-user chat as well as
              encrypting/signing messages and signing presence of the
              user. It is multilingual and runs on GNU/Linux, Mac OS X
              and Windows.
