#+TITLE: GnuPG - Related Software
#+STARTUP: showall
#+SETUPFILE: "../share/setup.inc"

* Related Software

  Over the years, GnuPG has widly gained in popularity to become the
  standard /de-facto/ as free software for private communication and
  digital signature. As such, it is by no mean surprisingly to find
  out that there are so many programms orbiting around GnuPG.

  For your convenience, GnuPG-related software has been grouped here in
  three big categories. If you are working for a new project and want to
  be listed here, please, feel free to contact the [[mailto:webmaster@gnupg.org][webmaster]] .

  Please note that, being part of the [[http://www.gnu.org/][GNU Project]], we can not link to
  any project which can not be labeled as [[http://www.gnu.org/philosophy/free-sw.html][free software]] . If you found
  a link on these pages to a project which does not fulfill this
  requirement (a good checkpoint is the [[http://directory.fsf.org/][ FSF/UNESCO Free Software
  Directory]]) please let us know by contacting the [[mailto:webmaster@gnupg.org][webmaster]] .

  -  [[file:frontends.org][Frontends]] :: This category collects together all the software for
                  various platforms which relays on GnuPG command line
                  and provides some sort of easy-to-use user
                  interface.
  -  [[file:tools.org][Tools]] :: Under this link you'll find tools mostly used to manage
              GnuPG keys.
  -  [[file:libraries.org][Libraries]] :: This page hosts projects which aim is to build an
                  abstraction layer for who wants to painlessly add
                  GnuPG capabilities to their software.
  -  [[file:swlist.org][All]] :: Direct access to all descriptions.
