#+TITLE: GnuPG - Libraries
#+STARTUP: showall
#+SETUPFILE: "../share/setup.inc"
#+OPTIONS:  ^:{}

* Libraries

  This page collects libraries related to GnuPG project.

  If you feel wanting to improve this list, please, fill in a [[https://www.gnupg.org/documentation/bts.html][Problem
  Report]] form.

** Libraries required to build GnuPG

  The libraries are requred to build currenrt GnUPG versions but may
  also be used on its onw.  They are maintained by the GnuPG Project.

   -  [[file:libgpg-error/index.org][Libgpg-error]] :: Libgpg-error is helper library used by a couple
                      of other projects to provide a common set of
                      error codes and descriptions.
   -  [[file:libgcrypt/index.org][Libgcrypt]] :: Libgcrypt is a general purpose cryptographic
                   library based on the code from GnuPG. It provides
                   functions for all cryptographic building blocks:
                   symmetric ciphers, hash algorithms, MACs, public
                   key algorithms, large integer functions, random
                   numbers and a lot of supporting functions.
   -  [[file:libassuan/index.org][Libassuan]] :: Libassuan is the IPC library used by some GnuPG
                   related software.
   -  [[file:libksba/index.org][Libksba]] :: Libksba provides an easy API to create and parse
                 X.509 and CMS related objects.
   -  [[file:npth/index.org][nPth]] :: The New GNU Portable Threads Library.


** Libraries recommended for use with GnuPG

   These libraries are not required to build GnuPG but are recommended
   by the GnuPG Project.

   -  [[file:gpgme/index.org][GPGME]] :: GnuPG Made Easy is a library designed to make access to
               GnuPG easier for applications.

** Other Libraries

   -  [[file:swlist.org::#gnupg-for-java][gnupg-for-java]] :: Java binding for GPGME
   -  [[file:swlist.org::#egd][EGD]] :: Entropy Gathering Daemon

# eof
