#+TITLE: GnuPG - Libraries
#+STARTUP: showall
#+SETUPFILE: "../share/setup.inc"
#+OPTIONS:  ^:{}

* Libraries

  This page collects libraries related to GnuPG project.

  If you feel wanting to improve this list, please, fill in a [[#gpgweb][Problem
   Report]] form.

   -  [[file:swlist.org::#egd][EGD]] :: Entropy Gathering Daemon
   -  [[file:swlist.org::#gpgme][GPGME]] :: GnuPG Made Easy
   -  [[file:swlist.org::#gnupg-for-java][gnupg-for-java]] :: Java binding for GPGME
   -  [[file:libassuan/index.org][libassuan]] :: Libassuan is the IPC library used by some GnuPG
                   related software.
   -  [[http://directory.fsf.org/wiki/Libgcrypt][libgcrypt]] :: Libgcrypt is a general purpose cryptographic
                   library based on the code from GnuPG. It provides
                   functions for all cryptographic building blocks:
                   symmetric ciphers, hash algorithms, MACs, public
                   key algorithms, large integer functions, random
                   numbers and a lot of supporting functions.
   -  [[file:libgpg-error/index.org][libgpg-error]] :: Libgpg-error is helper library used by a couple
                      of other projects to provide a common set of
                      error codes and descriptions.
   -  [[file:libksba/index.org][libksba]] :: Libksba provides an easy API to create and parse
                 X.509 and CMS related objects.

# eof
