#+TITLE: GnuPG - Mailing lists
#+STARTUP: showall indent
#+SETUPFILE: "../share/setup.inc"
#+OPTIONS: ^:{}

* Mailing lists

The contents of all messages sent to these mailing lists are assumed
to be in the public domain.  Archives of these mailing lists are also
available; please click on the mailing list name below.

Please check the [[file:faqs.org][FAQ]] before you ask on one of the lists.  If you want
to search these mailing lists (as well as other archives) please use
the service provided at [[http://marc.info/]].  If you do not want to
write to a public mailing list, check out the [[../service.org][commercial support]]
options.

| Name           | Purpose                                     | Lang |
|----------------+---------------------------------------------+------|
|                |                                             |      |
| [[http://lists.gnupg.org/pipermail/gnupg-announce/][gnupg-announce]] | Release announcements (low-traffic)         | en   |
|                |                                             |      |
| [[http://lists.gnupg.org/pipermail/gnupg-users/][gnupg-users]]    | General discussion and help                 | en   |
| [[http://lists.gnupg.org/pipermail/gnupg-br/][gnupg-br]]       | Help among Portuguese/Brazil speaking users | br   |
| [[http://lists.gnupg.org/pipermail/gnupg-de/][gnupg-de]]       | Help among German speaking users            | de   |
| [[http://lists.gnupg.org/pipermail/gnupg-pt/][gnupg-pt]]       | Help among Portuguese speaking users        | pt   |
| [[http://lists.gnupg.org/pipermail/gnupg-es/][gnupg-es]]       | Help among Spanish speaking users           | es   |
| [[http://lists.gnupg.org/pipermail/gnupg-ru/][gnupg-ru]]       | Help among Russian speaking users           | ru   |
|                |                                             |      |
| [[http://lists.gnupg.org/pipermail/gnupg-devel/][gnupg-devel]]    | Development discussion and bug tracking     | en   |
| [[http://lists.gnupg.org/pipermail/gcrypt-devel/][gcrypt-devel]]   | Development of Libgcrypt                    | en   |
| [[http://lists.gnupg.org/pipermail/gnupg-doc/][gnupg-doc]]      | Development of documentation                | en   |
| [[http://lists.gnupg.org/pipermail/gnupg-commits/][gnupg-commits]]  | Commit messages (read-only)                 | en   |
|                |                                             |      |
|----------------+---------------------------------------------+------|


A complete list of all mailing lists can also be found at our
[[https://lists.gnupg.org/mailman/listinfo/][mailing list manager]].

You may subscribe to these lists [[https://lists.gnupg.org/][via web]] or by sending an e-mail:

#+begin_example
  To: <mailing_list>-request@gnupg.org
  Subject: subscribe
#+end_example

where /<mailing_list>/ is the name of the mailing list as described
above.

Posting to these mailing lists is only allowed for subscribers;
postings from non-subscribers are held for approval but there is no
guarantee that the moderator can approve them in time; they may even
be dropped.

Some kinds of postings will not be accepted: e.g. large ones, mails
without the list name in the =To:= or =CC:= header and HTML mails.
All mail clients have an option to send plain text only messages; try
this if you don’t get a response.

Please write to the mailing lists in English unless it is language
specific list.

** Other discussion groups

There are also several other country-specific mailing-lists to
subscribe to.  It is important to note that these mailing-lists are
not hosted on the GnuPG servers, but are of great help for all of
those who feel more confortable when speaking their own native
language.

-  [[http://www.egroups.co.jp/group/gnupgnewsjapan/][GnuPG News Japan]] :: Discussion group for Japanese users.
-  [[http://itlists.org/mailman/listinfo/gnupg-it/][gnupg-it]] :: Mailing list dedicated to GnuPG users who speak Italian.

* IRC and Jabber

The channel =#gnupg= on =irc.freenode.org= is a place to talk about
all gnupg related topics.

The core GnuPG developers use the MUC =gnupg-devel= at conference dot
jabber dot gnupg.org for their day to day work.  Visitors are welcome.
