#+TITLE: GnuPG - GIT Access
#+STARTUP: showall
#+SETUPFILE: "../share/setup.inc"
#+GPGWEB-NEED-SWDB

* GIT Access

  The GnuPG development is tracked using the Git distributed revision
  control system.  A public read-only Git repository for GnuPG and
  related projects is available.

  This service is provided to help you in hunting bugs and not to
  deliver stable snapshots; it may happen that it even does not
  compile, so please don't complain.  Git may put a high load on a
  server, so please don't poll for new pushes too often. Instead, we
  suggest you use notifications from
  https://dev.gnupg.org/source/gnupg.git which mirrors the
  repositories.

  There is a Web interface at [[https://git.gnupg.org/]] which can be used
  to browse the GIT repository.

  All repositories have been migrated to Git from the old Subversion
  (SVN) code management tool. The standard way you checkout from an
  anonymous GIT is to clone the entire repository from one of these
  repositories:

#+BEGIN_EXAMPLE
  git clone https://dev.gnupg.org/source/gnupg.git
  git clone git://git.gnupg.org/gnupg.git
#+END_EXAMPLE

  You must run =./autogen.sh= before running the =./configure= in the
  way suggested by the output of =autogen.sh=.  This creates some
  required files which are not stored in the repository. =autogen.sh=
  also checks that you have all required tools installed. Please read
  the GIT manual pages before doing so.  The current stable
  version is {{{gnupg24_ver}}} and known as {{{gnupg24_branch}}}; the
  long term support (LTS) version is {{{gnupg22_ver}}} and known as
  {{{gnupg22_branch}}}; the legacy 1.4 version of GnuPG
  ({{{gnupg1_ver}}}) is known as STABLE-BRANCH-1-4.

  Bug reports should go to the developers mailing list. See the page
  on [[../documentation/mailing-lists.org][mailing lists]] .


** Other Hosted Projects

   The GnuPG Git server also hosts some other projects in Git
   repositories.  Please use the web interface at
   [[https://git.gnupg.org/]] to browse them.
