#+TITLE: GnuPG - GIT Access
#+STARTUP: showall
#+SETUPFILE: "../share/setup.inc"
#+GPGWEB-NEED-SWDB

* GIT Access

  The GnuPG development is tracked using the GIT distributed revision
  control system.  A public read-only GIT repository for GnuPG and
  related projects is available.

  This service is provided to help you in hunting bugs and not to
  deliver stable snapshots; it may happen that it even does not
  compile, so please don't complain.  GIT may put a high load on a
  server, so please don't poll for new pushes too often. Instead, we
  suggest you to subscribe to the [[https://lists.gnupg.org/mailman/listinfo/gnupg-commits/][commits mailing list]] .

  You may also follow [[https://twitter.com/gnuprivacyguard][@gnuprivacyguard]] on Twitter to get notified
  about commits to the GnuPG master branch.

  There is a Web interface at [[https://git.gnupg.org/]] which can be used
  to browse the GIT repository.

  All repositories have been migrated to GIT from the old Subversion
  (SVN) code management tool. The standard way you checkout from an
  anonymous GIT is to clone the entire repository:

#+BEGIN_EXAMPLE
  git clone git://git.gnupg.org/gnupg.git
#+END_EXAMPLE

  You must run =./autogen.sh= before running the =./configure= in the
  way suggested by the output of =autogen.sh=.  This creates some
  required files which are not stored in the repository. =autogen.sh=
  also checks that you have all required tools installed. Please read
  the GIT manual pages before doing so. The =master= revision is the
  development branch; the stable 2.0 version (currently version
  {{{gnupg_ver}}}) is known as =STABLE-BRANCH-2-0=; the old 1.4
  version of GnuPG ({{{gnupg1_ver}}}) is known as =STABLE-BRANCH-1-4=.

  Bug reports should go to the developers mailing list. See the page
  on [[../documentation/mailing-lists.org][mailing lists]] .


** Other Hosted Projects

   The GnuPG GIT server also hosts some other projects in GIT
   repositories.  Please use the web interface at
   [[https://git.gnupg.org/]] to browse them.
