#+TITLE: GnuPG - Supported Systems
#+STARTUP: showall
#+SETUPFILE: "../share/setup.inc"

* Supported Systems

  GnuPG works very well on almost all 32 and 64 bit platforms.

  It works fine on *GNU/Linux* with amd64, x86, alpha, mips, sparc64,
  armhf, arm64, m68k, or PowerPC CPUs. (amd64 is the primary development system, the other
  CPUs are only checked from time to time.)

  64 bit versions of *Windows* 10 and 11 are very well supported.

  *MacOS X* is also supported; please see [[https://gpgtools.org/][gpgtools.org]] for detailed
  information.

  *OpenBSD*, *FreeBSD*, *NetBSD*, *AIX*, and *Solaris* are fully supported.

** Other OSes

  *The information in this section is considered outdated!*

  It compiles okay on *GNU/Hurd* but because Mach has no random
  device, it should not be used for real work. Work is underway to add
  an random device.

  A port of GnuPG to *VMS* is available at
  [[http://antinode.info/dec/sw/gnupg.html][http://antinode.info/dec/sw/gnupg.html]].

   GnuPG compiles and runs on many more systems, but due to the lack
   of a well tested entropy source, it /should be used with some
   caution/. We have positive reports on these systems:

   -  *BSDI* v4.0.1 with i386
   -  *HPUX* v9.x, v10.x and v11.0 with HPPA CPU
   -  *IRIX* v6.3 with MIPS R10000 CPU
   -  *MP-RAS* v3.02
   -  *OSF1* V4.0 with Alpha CPU
   -  *OS/2* version 2
   -  *SCO* UnixWare/7.1.0
   -  *SunOS* on Sparc and x86
   -  *USL Unixware* v1.1.2
