#+TITLE: GnuPG e.V.
#+STARTUP: showall
#+SETUPFILE: "../share/setup.inc"
#+macro: atgit [[https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg-verein.git;a=blob_plain;f=$1][$2]]

* The GnuPG e.V. has been dissolved

The GnuPG e.V. was a charitable legal person (a German “Verein”) to
improve data protection, data sovereignty and customer protection in
in our supranational networked society.  To achieve these goals the
Verein seeks for international cooperation with people and
organizations and supports the development and distribution of Free
and Open Source software.

The Verein was founded on February 8, 2017 by 7 active GnuPG
developers.  Its registration number is /VR11482/ at /Amtsgericht
Düsseldorf/.  The tax office Düsseldorf-Altstadt confirmed the
charitable state.

The membership assembly decided on 2024-08-17 to dissolve the Verein.
The Amtsgericht Düsseldorf registered the termination on 2025-02-19.

Creditors should check the "Amtsblatt für den Regierungsbezirk
Düsseldorf, Amtsblatt Nr. 16, Öffdentlicher Anzeiger vom 17.04.2025,
Ziffer 112" on how to contact the liquidator.

# eof
