#+TITLE: GnuPG e.V.
#+STARTUP: showall indent
#+SETUPFILE: "share/setup.inc"
#+macro: atgit [[https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg-project.git;a=blob_plain;f=$1][$2]]

* The GnuPG e.V.

In February 2017 several GnuPG developer came together for a 3 day
hackathon.  While having some beer in the [[http://www.bilkinfo.de/kneipen/tigges.html][Tigges]] on one evening the
lingering plan for setting up a legal entity was finally agreed upon.
Work on the constitution started right away and the founding assembly
commenced on the next day at 13:37.

The 7 founding members are: Andre Heinecke, Justus Winter, Kai
Michaelis, Marcus Brinkmann, Neal Walfied, Werner Koch, and Yutaka
Niibe.  The elected chair is Werner, the vice Andre, and the cashier
Marcus.  The registration number is /VR11482/ at /Amtsgericht
Düsseldorf/.

Our {{{atgit(legal/constitution.de.pdf,constitution)}}} is written in
German; a legally non-binding
{{{atgit(legal/constitution.en.pdf,translation)}}} is available.  The
founding protocol can can be read
{{{atgit(legal/founding-protocol-20170208.txt,here)}}}.

The rules on how to apply for membership will soon be posted.  We will
also soon apply for charitable status so that donations will be tax
exempted at least in Germany.
