#+TITLE: GnuPG - Donate - Checkout with card
#+STARTUP: showall
#+SETUPFILE: "../share/setup.inc"

#+BEGIN_HTML
<!--custom-page-->  <!-- this disables all standard processing. -->
<link rel="stylesheet" href="/share/site.css" type="text/css" />
</head>
<body lang="en">

<p>
Information on your intended donation:
</p>

<table border="0" cellpadding="0" cellspacing="4" id="checkoutSummary">
 <tr>
   <td align="right">Amount:</td>
   <td><!--AMOUNT-->
       <!--CURRENCY-->
       <!--RECUR_TEXT--></td>
 </tr>
 <tr>
   <td align="right">Name:</td>
   <td><!--NAME--></td>
 </tr>
 <tr>
   <td align="right">Mail:</td>
   <td><!--MAIL--></td>
 </tr>
 <tr>
   <td align="right" valign="top">Message:</td>
   <td><!--MESSAGE_FMT--></td>
 </tr>
</table>

<p>
  If something is wrong, please use the back button below to change
  it.  If the data is correct, you may now continue with the payment.
</p>

  <noscript>
    <p>
      <strong>Please enable Javascript.</strong>
    </p>
    <p id="smallnote">
       Right, for security reasons it is in general preferable to
       disable Javascript in a browser.  However, we do not want
       to handle credit card numbers ourselves and use a service of
       our payment processor to convey this sensitive information
       directly between your browser and them.  This requires that
       you enable enable Javascript for <emph>gnupg.org</emph>
       and <emph>stripe.com</emph>.
    </p>
  </noscript>

  <!--ERRORSTR-->
  <div class="buttonbox">
  <p>
    <form action="/cgi-bin/procdonate.cgi" method="POST">
      <input type="hidden" name="mode" value="checkout-stripe">
      <input type="hidden" name="sessid" value="<!--SESSID-->">
      <script
        src="https://checkout.stripe.com/checkout.js"
        class="stripe-button"
        data-key="<!--STRIPEPUBKEY-->"
        data-image="/share/gnupg-badge-128x128.png"
        data-name="GnuPG"
        data-description="Donation to the GnuPG project"
        data-amount="<!--STRIPEAMOUNT-->"
        data-currency="<!--CURRENCY-->"
        data-panel-label="Donate {{amount}} <!--RECUR_TEXT-->"
        data-label="<!--STRIPE_DATA_LABEL_VALUE-->"
        <!--STRIPE_DATA_EMAIL-->
      >
      </script>
    </form>
  </p>
  <form action="/cgi-bin/procdonate.cgi" method="POST">
    <input type="hidden" name="mode" value="re-main">
    <input type="hidden" name="sessid" value="<!--SESSID-->">
    <input type="submit" class="donate-button-low" value="Back" />
  </form>
  </div>

</body>
</html>
#+END_HTML
