#+TITLE: GnuPG - Donate
#+STARTUP: showall
#+SETUPFILE: "../share/setup.inc"
#
# Note: Do not use relative links because this page is also used as a
#       template from cgi-bin/.  Using https://www.gnupg.org/... is
#       fine as it is stripped before publishing.


* GnuPG needs your support to help protect online privacy.

  Activists, journalists, lawyers, and many others rely on GnuPG to
  protect their communication.  And, nearly all free software-based
  operating systems (which are used by more than two-thirds of the
  servers running the Internet) rely on GnuPG to verify the integrity
  of system updates.

  GnuPG development is mainly financed by donations.  Aside of the
  large donors Linux Foundation, Stripe, Facebook, and First Look
  Media, we received a lot of individual donations.  Our fundraising
  [[file:camp2017.org][campaign]] in 2017 also raised about 5000 Euro in monthly recurring
  donations.

  *Many thanks to all supporters*

  If you are using [[../software/index.org][GnuPG]], [[../software/libgcrypt/index.org][Libgcrypt]], [[../software/gpgme/index.org][GPGME]], or [[https://www.gpg4win.org][Gpg4win]] and would like
  to help with development and maintenance please consider to make a
  donation.


#+BEGIN_HTML
<div class="col-xs-12 col-sm-6 col-lg-12">
  <a class="btn btn-primary btn-lg btn-block" role="button"
     href="/cgi-bin/procdonate.cgi?mode=preset&plan=12-10-eur"
     >Donate 10&thinsp;€ a month</a>
  <div class="row" style="margin-top: 1em;">
    <div class="col-xs-6">
      <a class="btn btn-default btn-md btn-block" role="button"
         href="/cgi-bin/procdonate.cgi?mode=preset&plan=12-5-eur"
         >5&thinsp;€ a month</a>
    </div>
    <div class="col-xs-6">
      <a class="btn btn-default btn-md btn-block" role="button"
         href="/cgi-bin/procdonate.cgi?mode=preset&plan=12-20-eur"
         >20&thinsp;€ a month</a>
    </div>
  </div>
  <div class="row text-center" style="margin-top: 1em;">
    <a style="margin-top: 1em;"
       href="/cgi-bin/procdonate.cgi?mode=preset"
       >Donate a different amount</a>
  </div>
</div>
#+END_HTML



** Recent donors

#+BEGIN_HTML
<div id="tagcloudlist"><ul>
<!--BEGIN-SOME-DONATIONS-->
<!--END-SOME-DONATIONS-->
<li><a href="/donate/kudos.html">(all)</a></li>
</ul><p class="doclear"> </p></div>
<p>Donations received in
<!--INSERT-THIS-YEAR-->
:&nbsp;
<!--INSERT-YEAR-EURO-->
</p>
#+END_HTML

# eof #
