#+TITLE: GnuPG - Donate
#+STARTUP: showall
#+SETUPFILE: "../share/setup.inc"
#
# Note: Do not use relative links because this page is also used as a
#       template from cgi-bin/.  Using https://www.gnupg.org/... is
#       fine as it is stripped before publishing.


* GnuPG used to ask for your support to help protect online privacy

  Activists, journalists, lawyers, and many others rely on GnuPG to
  protect their communication.  And, nearly all free software-based
  operating systems (which are used by more than two-thirds of the
  servers running the Internet) rely on GnuPG to verify the integrity
  of system updates.

  GnuPG development was mainly financed by donations.  Aside of the
  large donors Linux Foundation, Stripe, Facebook, and First Look
  Media, we received a lot of individual donations.  Our fundraising
  [[file:camp2017.org][campaign]] in 2017 also raised about 5000 Euro in monthly recurring
  donations.

  *Many thanks to all supporters*

  Fortunately, and this is still not common with free software, we
  have now established a way of financing the development while
  keeping all our software free and freely available for everyone.

  Our model is similar to the way RedHat manages RHEL and Fedora:
  Except for the actual binary of the MSI installer for Windows and
  client specific configuration files, all the software is available
  under the GNU GPL and other Open Source licenses.  Thus customers
  may even build and distribute their own version of the software as
  long as they do not use our trademark /GnuPG VS-Desktop^{\reg}/.

  Those with *SEPA donations, please cancel them and redirect* your
  funds to other projects which are more in need of financial support.
  The donations done via Stripe or PayPal have already been canceled.

  All you supporters greatly helped us to keep GnuPG alive and to
  finally setup a sustainable development model.  Stay tuned for a
  somewhat longer writeup on this.

  *Thanks.*


# eof #
