#+TITLE: GnuPG - Donate
#+STARTUP: showall
#+SETUPFILE: "../share/setup.inc"
#
# Note: Do not use relative links because this page is also used as a
#       template from cgi-bin/.  Using https://www.gnupg.org/... is
#       fine as it is stripped before publishing.


* Donate

  Maintaining and improving GnuPG is costly. For more than a decade,
  [[https://g10code.com][g10^code]] GmbH, a company owned and headed by GnuPG's principal
  author Werner Koch, is bearing the majority of these costs. To help
  them carry on this work, they need your support.  Note that despite
  GnuPG carries an [[https://www.fsf.org][FSF]] copyright notice, they never funded the
  development or hosting costs.

  If you are using [[../index.org][GnuPG]], [[../software/libgcrypt/index.org][Libgcrypt]], [[../software/gpgme/index.org][GPGME]], or [[https://www.gpg4win.org][Gpg4win]] and would like
  to help with development and maintenance please consider to make a
  donation.

** Ways to donate

  Paying using a credit card is currently our preferred choice.  If
  you have a Paypal account you may use that too.

  Because the GnuPG project is not tax exempted, we are not able to
  send you a respective donation receipt.  If you represent a company,
  you may also enter into a support contract with
  [[https://g10code.com][g10^code]] or ask for other service options.

#+BEGIN_HTML

  <ul>
    <li><a href="/cgi-bin/procdonate.cgi?mode=preset"
           >One time donation</a></li>
    <li><a href="/cgi-bin/procdonate.cgi?mode=preset&plan=12-10-eur"
           >Donate 10&thinsp;&euro; a month</a></li>
    <li><a href="/cgi-bin/procdonate.cgi?mode=preset&plan=12-20-eur"
           >Donate 20&thinsp;&euro; a month</a></li>
  </ul>

#+END_HTML


** Recent donors

#+BEGIN_HTML
<div id="tagcloudlist"><ul>
<!--BEGIN-SOME-DONATIONS-->
<!--END-SOME-DONATIONS-->
<li><a href="/donate/kudos.html">(all)</a></li>
</ul><p class="doclear"> </p></div>
<p>Donations received in
<!--INSERT-THIS-YEAR-->
:&nbsp;
<!--INSERT-YEAR-EURO-->
</p>
#+END_HTML

# eof #
