#+TITLE: GnuPG - Donate
#+STARTUP: showall
#+SETUPFILE: "../share/setup.inc"
#
# Note: Do not use relative links because this page is also used as a
#       template from cgi-bin/.  Using https://www.gnupg.org/... is
#       fine as it is stripped before publishing.


* Donate

  Maintaining and improving GnuPG is costly. For more than a decade,
  [[https://g10code.com][g10^code]] GmbH, a company owned and headed by GnuPG's principal
  author Werner Koch, is bearing the majority of these costs. To help
  them carry on this work, they need your support.  Note that despite
  GnuPG carries an [[https://www.fsf.org][FSF]] copyright notice, they never funded the
  development or hosting costs.

  If you are using [[../index.org][GnuPG]], [[http://directory.fsf.org/project/libgcrypt/][Libgcrypt]], [[../related_software/gpgme/index.org][GPGME]], or [[https://www.gpg4win.org][Gpg4win]] and would like
  to help with development and maintenance please consider to make a
  donation.

** Recent donors

#+HTML: <div id="tagcloudlist"><ul>
#+HTML: <!--BEGIN-SOME-DONATIONS-->
#+HTML: <!--END-SOME-DONATIONS-->
#+HTML: <li><a href="/donate/kudos.html">(all)</a></li>
#+HTML: </ul><p class="doclear"> </p></div>


** Ways to donate

  Paying using a credit card is currently our preferred choice.  If
  you have a Paypal account you may use that too.

  Because the GnuPG project is not tax exempted, we are not able to
  send you a respective donation receipt.  If you can benefit from a
  donation receipt by a Germany charity you may donate to the GnuPG
  account at the [[https://www.wauland.de/en/donation.html#61][Wau Holland Stiftung]]; they will use the money raised
  to pay for development work on GnuPG and Enigmail.  If you want to
  be listed on our [[https://www.gnupg.org/donate/kudos.html][thank you]] page you should indicate this by adding a
  comment of the form =List me as: NAME= to your donation.

  If you represent a company, you may also enter into a support
  contract with [[https://g10code.com][g10^code]] or ask for other service options.

** Donation form

  To process your donation we need to collect some information.  This
  information is only used for the purpose of the donation and no data
  will ever be send to any entity not directly involved in the
  donation process.  Not giving a name makes the donation “anonymous”
  in that the name won’t be listed on the public [[https://www.gnupg.org/donate/kudos.html][thank you]] page.

#+BEGIN_HTML
  <!--ERRORPANEL-->

  <form action="/cgi-bin/procdonate.cgi" method="post" class="inputpanel">
   <input type="hidden" name="mode" value="main">
   <p class="ii">Keep this field clear:
                 <input type="text" size="40" name="url"></p>
   <table border="0" cellpadding="0" cellspacing="4">
    <tr>
      <td></td>
      <td>How much do you want to donate?<br/>
          <span class="smallnote">(choosing “other” allows
          to donate in other currencies)</span></td>
    </tr>
    <tr>
      <td align="right">Amount:</td>
      <td>
          <label><input type="radio" name="amount" value="500"/>500 EUR</label>
          <label><input type="radio" name="amount" value="200"/>200 EUR</label>
          <label><input type="radio" name="amount" value="100"/>100 EUR</label>
          <label><input type="radio" name="amount" value="50"/>50 EUR</label>
          <label><input type="radio" name="amount" value="20"/>20 EUR</label>
          <label><input type="radio" name="amount" value="5"/>5 EUR</label>
      </td>
    </tr>
    <tr>
      <td></td>
      <td>
          <input type="radio" name="amount"
                              value="other"/><!--CHECKOTHER-->other:
          <input type="text"  size="6" name="amountother"
                              value=""/><!--AMOUNT-->
          <select name="currency" size="1">
            <option value="EUR" selected="selected"><!--SEL_EUR-->Euro</option>
            <option value="USD" ><!--SEL_USD-->US Dollar</option>
            <option value="GBP" ><!--SEL_GBP-->British Pound</option>
            <option value="JPY" ><!--SEL_JPY-->Yen</option>
          </select>
          <!--ERR_AMOUNT-->
      </td>
    </tr>
   <tr><td>&nbsp;</td></tr>
    <tr>
      <td align="right">Pay&nbsp;using:</td>
      <td>
        <label><input type="radio" name="paytype"
                      value="cc" /><!--CHECK_CC-->Credit Card</label>
        <!--ERR_PAYTYPE-->
      </td>
   </tr>
   <tr>
     <td></td>
     <td>
       <label><input type="radio" name="paytype"
                     value="pp" /><!--CHECK_PP-->PayPal</label>
     </td>
   </tr>
   <tr><td>&nbsp;</td></tr>
   <tr>
      <td></td>
      <td>
          If you want to be listed on the
          <a href="/donate/kudos.html">list of donors</a>,
          please enter your name as it shall appear there.
      </td>
    </tr>
    <tr>
      <td align="right"><label for="f_name">Name:</label></td>
      <td>
          <input id="f_name" type="text"
                 size="40" style="width:200px" name="name"
                 value=""/><!--NAME--> (optional)
          <!--ERR_NAME-->
      </td>
    </tr>
    <tr>
      <td></td>
      <td>
          In case of payment problems we may want to contact you, thus please
          enter your mail address.
      </td>
    </tr>
    <tr>
      <td align="right"><label for="f_mail">Mail:</label></td>
      <td>
          <input id="f_mail" type="text" size="40" style="width:200px"
                 name="mail"
                 value=""/><!--MAIL--> (optional)
           <!--ERR_MAIL-->
      </td>
    </tr>
    <tr>
      <td></td>
      <td>
          If you want to leave a message for us, please enter it here:
      </td>
    </tr>
    <tr>
      <td></td>
      <td>
          <textarea cols="40" rows="4" style="width:500px" name="message"
                    ></textarea><!--MESSAGE-->
      </td>
    </tr>
    <tr>
      <td></td>
      <td>
        <div class="buttonbox">
          <input type="submit" class="donate-button-low"
                 value="Proceed to checkout" />
         </div>
      </td>
    </tr>
   </table>
  </form>
#+END_HTML
