#!/bin/sh

set -e

if [ "$(pwd  | awk -F/ '{print $NF}')" != "blog.gnupg.org" ]; then
  echo "upload: not invoked from the blog.gnupg.org directory" >&2;
  exit 1
fi

rsync -vr --links --exclude '*~' --exclude upload \
   . werner@trithemius.gnupg.org:/var/www/www/www.gnupg.org/misc/blog/

#eof
