#!/bin/sh

set -e

if [ "$(pwd  | awk -F/ '{print $NF}')" != "blog.gnupg.org" ]; then
  echo "upload: not invoked from the blog.gnupg.org directory" >&2;
  exit 1
fi

echo "upload: Rendering entries" >&2
# We need to initialize that org cache to use our own publish function
# despite that we do not use any org-publish feature
emacs23 --batch \
  --eval "(require 'assoc)" \
  --eval "(require 'org)" \
  --eval "(setq gpgweb-root-dir \"$(cd ../../web && pwd)/\")" \
  --eval "(require 'gpgweb (concat gpgweb-root-dir \"share/gpgweb.el\"))" \
  --eval "(setq org-publish-use-timestamps-flag nil)" \
  --eval "(setq org-export-html-toplevel-hlevel 1)" \
  --eval "(setq org-export-html-coding-system 'utf-8)" \
  --eval "(gpgweb-setup-project)" \
  --eval "(org-publish-initialize-cache \"gpgweb\")" \
  --eval "(gpgweb-publish-blogs)"

if [ ! -f index.html ]; then
  echo "upload: index.html has not yet been build" >&2;
  exit 1
fi

# Find all rendered HTML files but skip possible translated versions.
find . -maxdepth 1 -type f -name "20*.html" -print \
    | grep -v '\.[a-z][a-z].html$' | sort -r >index.tmp
newest=$(head -1 index.tmp)

# Extract the head lines
: >index.headlines.tmp
cat index.tmp | while read fname; do
  echo -n "${fname#./}|" >>index.headlines.tmp
  sed  -n '/^<h2 id=/ s,^<[^>]*>\(.*\)</h2>,\1,p' $fname >>index.headlines.tmp
done

# Update the index file
echo "upload: Updating index.html" >&2
awk -F:  <index.html  >index.tmp \
    -v newest=${newest#./} '
     /<!--BEGIN-NEWEST-ENTRY-->/ {indon=1; print; insertnewest() }
     /<!--END-NEWEST-ENTRY-->/ {indon=0}
     /<!--BEGIN-BLOG-INDEX-->/ {indon=1; print; insertindex() }
     /<!--END-BLOG-INDEX-->/   {indon=0}
     !indon { print }

     function insertnewest () {
       inblog = 0
       while (getline < newest) {
         if (match ($0, /^<main>/))  { inblog = 1; continue; }
         if (match ($0, /^<\/main>/)) { inblog = 0; break; }
         if (! inblog) { continue }
         if (match ($0, /^<div id="content">/)) { continue; }
         if (match ($0, /^<\/div><!-- end content -->/)) { continue; }
         print $0
       }
      close(newest)
     }

     function insertindex (tag) {
       file = "index.headlines.tmp";
       print "<ul>"
       while (getline < file) {
         split($0, a, "|")
         printf "  <li><a href=\"%s\">%s</a>\n", a[1], a[2];
       }
       print "</ul>"
       close (file)
     }
     '
mv index.tmp index.html || echo "upload: error updating index.html" >&2

# Update the feed file
echo "upload: Updating feed file" >&2



# Remove temp file
rm index.headlines.tmp

echo "upload: Uploading files" >&2
rsync -vr --links --exclude '*~' --exclude upload --exclude '*tmp' \
   --exclude '*.org' \
   . werner@trithemius.gnupg.org:/var/www/www/www.gnupg.org/misc/blog/

#eof
