#+TITLE: The GNU Privacy Guard
#+STARTUP: showall
#+SETUPFILE: "share/setup.inc"

* The GNU Privacy Guard
#+index: GnuPG
#+index: GPG
#+index: PGP
#+index: Gpg4win

GnuPG is a complete and free implementation of the OpenPGP standard as
defined by [[http://www.ietf.org/rfc/rfc4880.txt][RFC4880]] (also known as /PGP/). GnuPG allows to encrypt and
sign your data and communication, features a versatile key management
system as well as access modules for all kinds of public key
directories. GnuPG, also known as /GPG/, is a command line tool with
features for easy integration with other applications. A wealth of
[[file:related_software/frontends.html][frontend applications]] and [[file:related_software/libraries.html][libraries]] are available. Version 2 of GnuPG
also provides support for S/MIME and Secure Shell (ssh).

GnuPG is [[http://www.gnu.org/philosophy/free-sw.html][Free Software]] (meaning that it respects your freedom). It can
be freely used, modified and distributed under the terms of the
[[http://www.gnu.org/copyleft/gpl.html][GNU General Public License]] .

GnuPG comes in three flavours:

 - {{{gnupg_ver}}} is the /stable/ version suggested for most users,

 - {{{gnupg21_ver}}} is the brand-new /modern/ version with support
   for [[https://en.wikipedia.org/wiki/Elliptic_curve_cryptography][ECC]] and many other new features,

 - and {{{gnupg1_ver}}} is the /classic/ portable version.

Project [[https://www.gpg4win.org][Gpg4win]] provides a Windows version of GnuPG /stable/. It is
nicely integrated into an installer and features several frontends as
well as English and German manuals.

* Reconquer your privacy

Even if you have nothing to hide, using encryption helps protect the
privacy of people you communicate with, and makes life difficult for
bulk surveillance systems. If you do have something important to hide,
you are in good company; GnuPG is one of the tools that Edward Snowden
used to uncover his secrets about the NSA.

Please visit the [[https://emailselfdefense.fsf.org][Email Self-Defense]] site to learn how and why you
should use GnuPG for your electronic communication.  If you need
printed leaflets check out [[https://fsfe.org/contribute/spreadtheword.html#gnupg-leaflet][FSFE’s GnuPG leaflet]].


* News
#+index: News

The latest blog entries:
#+begin_html
<ul>
<!--INSERT-BLOG-HEADLINE-->
</ul>
#+end_html

The latest release news:\\
([[file:news.org][all news]])

# For those of you who like reading world’s news with an RSS reader,
# GnuPG's latest news are available as [[http://feedvalidator.org/check.cgi?url%3Dhttps://www.gnupg.org/news.en.rss][RSS 2.0 compliant]] feed.  Just
# point or paste the [[news.en.rss][RSS file]] into your aggregator.


** Libgcrypt 1.6.5 released (2016-02-09) 			  :important:

Libgcrypt version 1.6.5 and an updated Windows installer for GnuPG
2.1.11 has been released to mitigate a new side-channel attack.
[[https://lists.gnupg.org/pipermail/gnupg-announce/2016q1/000384.html][{more}]]

** GnuPG 2.1.11 released (2016-01-26)

A new version of the /modern/ branch of GnuPG has been released.
Read the full [[https://lists.gnupg.org/pipermail/gnupg-announce/2016q1/000383.html][announcement mail]] for details.

** GnuPG 1.4.20 released (2015-12-20)

18 years after the first GnuPG release version 1.4.20 has been
released today.  This release from the /classic/ branch of GnuPG now
also rejects the insecure MD5 signatures created by PGP-2 (unless the
=--pgp2= option is used).  [[https://lists.gnupg.org/pipermail/gnupg-announce/2015q4/000382.html][{more}]]

** GnuPG 2.1.10 released (2015-12-04)

A new version of the /modern/ branch of GnuPG has been released.  The
main features of this release are support for [[https://en.wikipedia.org/wiki/Trust_on_first_use][TOFU]] and anonymous key
retrieval via [[https://www.torproject.org][Tor]].  Read the full [[https://lists.gnupg.org/pipermail/gnupg-announce/2015q4/000381.html][announcement mail]] for details.

** GnuPG 2.1.9 released (2015-10-09)

A new version of the /modern/ branch of GnuPG has been released.
Read the full [[https://lists.gnupg.org/pipermail/gnupg-announce/2015q4/000380.html][announcement mail]] for details.

** GnuPG 2.1.8 released (2015-09-10)

A new version of the /modern/ branch of GnuPG has been released.
Read the full [[https://lists.gnupg.org/pipermail/gnupg-announce/2015q3/000379.html][announcement mail]] for details.

** GPA 0.9.9 released (2015-09-09)

A new version of [[file:related_software/gpa/index.org][GPA]], the graphical frontend for GnuPG, is now
available.  This release fixes a couple of bugs and has been changed
to show the clipboard view on startup.  [[https://lists.gnupg.org/pipermail/gnupg-announce/2015q3/000378.html][{more}]]

** GnuPG 2.0.29 released (2015-09-08)

GnuPG 2.0.29 is now available.  This release fixes a couple of bugs;
users of GnuPG 2.0.x may want to update to this version.  [[https://lists.gnupg.org/pipermail/gnupg-announce/2015q3/000376.html][{more}]]

** Libgcrypt 1.6.4 released (2015-09-08)

Libgcrypt version 1.6.4 has been released to fix a few minor bugs and
a crash on newer Windows versions. [[https://lists.gnupg.org/pipermail/gnupg-announce/2015q3/000375.html][{more}]]

** Libassuan 2.3.0 released (2015-08-28)

[[file:related_software/libassuan/index.org][Libassuan]] is a generic [[https://en.wikipedia.org/wiki/Inter-process_communication][IPC]] library used by GnuPG, GPGME, and a few
other packages.  This release fixes two bugs and introduces new
support functions for the socket wrappers.  See [[https://lists.gnupg.org/pipermail/gnupg-announce/2015q3/000374.html][here]] for details.

** GPGME 1.6.0 and Libgpg-error 1.20 released (2015-08-26)

GPGME 1.6.0 is now available.  This release introduce a mode to export
sceret keys, improves the error return codes, and is prepared to make
use of the GnuPG 2.1 Windows installer.  See this full [[https://lists.gnupg.org/pipermail/gnupg-announce/2015q3/000372.html][announcement]].
An update of Libgpg-error to fix a problem in Windows has also been
released; see this [[https://lists.gnupg.org/pipermail/gnupg-announce/2015q3/000373.html][announcement]].

** GnuPG 2.1.7 released (2015-08-11)

A new version of the /modern/ branch of GnuPG has been released.
Read the full [[https://lists.gnupg.org/pipermail/gnupg-announce/2015q3/000371.html][announcement mail]] for details.

** GnuPG 2.1.6 released (2015-07-01)

A new version of the /modern/ branch of GnuPG has been released.
Read the full [[https://lists.gnupg.org/pipermail/gnupg-announce/2015q3/000370.html][announcement mail]] for details.


* A big Thanks to all supporters

Due to this [[http://www.propublica.org/article/the-worlds-email-encryption-software-relies-on-one-guy-who-is-going-broke][ProPublica article]] we received more than 120,000 \euro of
individual donations on a single day.  There was even more: The [[http://www.linuxfoundation.org/programs/core-infrastructure-initiative][Core
Infrastructure Initiative]] granted 60,000 $ for 2015.  Our payment
service [[https://twitter.com/stripe/status/563449352635432960][Stripe]] and [[https://www.facebook.com/notes/protect-the-graph/supporting-gnu-privacy-guard/1564591893780956][Facebook]] will each give 50,000 $ to the project.
And finally the [[https://www.wauland.de/en/donation.html#61][Wau Holland Stiftung]] is collecting tax deductible
funds for GnuPG (19000 \euro plus 57 BTC).

As the main author of GnuPG, I like to thank everyone for supporting
the project, be it small or large individual donations, helping users,
providing corporate sponsorship, working on the software, and for all
the encouraging words.

GnuPG does not stand alone: there are many other projects, often
unknown to most people, which are essential to keep the free Internet
running.  Many of them are run by volunteers who spend a lot of unpaid
time on them.  They need our support as well.

/--- Werner, 2015-02-06/

(see also this [[https://gnupg.org/blog/20150310-gnupg-in-february.html][blog]] entry)

* COMMENT
This is the publishing info used for the GnuPG pages
#+begin_src emacs-lisp
  (progn
   (setq gpgweb-root-dir (file-name-directory (buffer-file-name)))
   (require 'gpgweb (concat gpgweb-root-dir "share/gpgweb.el"))
   (setq org-publish-use-timestamps-flag nil)
   (setq org-export-html-toplevel-hlevel 1)
   (setq org-export-html-coding-system 'utf-8)
   (gpgweb-setup-project))
#+end_src
