#+TITLE: The GNU Privacy Guard
#+STARTUP: showall
#+SETUPFILE: "share/setup.inc"
#+GPGWEB-NEED-SWDB
#+HTML_HEAD_EXTRA: <link type="application/rss+xml" href="https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg-doc.git;a=rss;f=web/index.org"/>
#+HTML_HEAD_EXTRA: <link rel="stylesheet" href="/share/pure-min.css.gz" type="text/css" />
#+HTML_HEAD_EXTRA: <link rel="stylesheet" href="/share/grids-responsive-min.css.gz" type="text/css" />
# Note that the above html_head_extra lines do not work; you need to put such
# stuff this into share/gpgweb.wl

* The GNU Privacy Guard
#+index: GnuPG
#+index: GPG
#+index: PGP
#+index: Gpg4win

GnuPG is a complete and free implementation of the OpenPGP standard as
defined by [[https://www.ietf.org/rfc/rfc4880.txt][RFC4880]] (also known as /PGP/). GnuPG allows you to encrypt and
sign your data and communications; it features a versatile key management
system, along with access modules for all kinds of public key
directories.  GnuPG, also known as /GPG/, is a command line tool with
features for easy integration with other applications.  A wealth of
[[file:software/frontends.html][frontend applications]] and [[file:software/libraries.html][libraries]] are available.  GnuPG also
provides support for S/MIME and Secure Shell (ssh).

Since its introduction in 1997, GnuPG is [[https://www.gnu.org/philosophy/free-sw.html][Free Software]] (meaning that
it respects your freedom). It can be freely used, modified and
distributed under the terms of the [[https://www.gnu.org/copyleft/gpl.html][GNU General Public License]] .

The current version of GnuPG is {{{gnupg26_ver}}}.  See the [[file:download/index.org][download]]
page for other maintained versions.

[[https://www.gpg4win.org][Gpg4win]] is a Windows version of GnuPG featuring a context menu tool, a
crypto manager, and an Outlook plugin to send and receive standard
PGP/MIME mails.  The current version of Gpg4win is {{{gpg4win_ver}}}.

** <div class="pure-g">                                        :html:virtual:



* Reconquer your privacy
   :PROPERTIES:
   :HTML_CONTAINER_CLASS: pure-u-1 pure-u-md-1-2
   :END:

#+begin_quote
Arguing that you don't care about the right to privacy
because you have nothing to hide is no different from
saying you don't care about free speech because you have
nothing to say.   \ndash\nbsp{}Edward\nbsp{}Snowden
#+end_quote

Using encryption helps to protect your privacy and the privacy of the
people you communicate with.  Encryption makes life difficult for bulk
surveillance systems.  GnuPG is one of the tools that Snowden used to
uncover the secrets of the NSA.

Please visit the [[https://emailselfdefense.fsf.org][Email Self-Defense]] site to learn how and why you
should use GnuPG for your electronic communication.


* News
   :PROPERTIES:
   :HTML_CONTAINER_CLASS: pure-u-1 pure-u-md-1-2
   :END:
#+index: News

The latest blog entries:
#+begin_html
<ul>
<!--INSERT-BLOG-HEADLINE-->
</ul>
#+end_html

The latest release news:\\
([[file:news.org][all news]])

# For those of you who like reading world’s news with an RSS reader,
# GnuPG's latest news are available as [[http://feedvalidator.org/check.cgi?url%3Dhttps://www.gnupg.org/news.en.rss][RSS 2.0 compliant]] feed.  Just
# point or paste the [[news.en.rss][RSS file]] into your aggregator.

** Security advisory T8044 for GnuPG and Gpg4win                  :important:

GnuPG 2.5.17 and Gpg4win 5.0.1 have been released to fix a severe
security bug in GnuPG versions 2.5.13 to 2.5.16.  *Please update as
soon as possible*.

{[[https://lists.gnupg.org/pipermail/gnupg-announce/2026q1/000501.html][Read more]]}

** Debian packages for 2.5.16 are available (2026-01-06)

GnuPG 2.5.16 packages for [[https://debian.org][Debian]], [[https://devuan.org][Devuan]], and [[https://ubuntu.com][Ubuntu]] are now available
at their usual place [[https://repos.gnupg.org/deb/gnupg][repos.gnupg.org]] - please consired to update.

** GnuPG 2.5.16 released (2025-12-30)

We are pleased to announce the availability of a new stable GnuPG release:
Version 2.5.16.  This release adds new features and fixes a couple of
bugs.

Note that the 2.5 series is now declared the stable version of GnuPG.
Be aware that the oldstable 2.4 series will reach end-of-life in just
6 months.

{[[https://lists.gnupg.org/pipermail/gnupg-announce/2025q4/000500.html][Read more]]}

** GnuPG 2.5.14 released (2025-11-19)

We are pleased to announce the availability of a new GnuPG release:
Version 2.5.14.  This release adds new features and fixes a couple of
bugs.  New Debian packages are also also availabe; see
[[https://repos.gnupg.org/deb/gnupg/trixie-devel/][repos.gnupg.org]].

Note that this 2.5 series is fully supported and thus ready for
production use.  This means we won't break anything but may add some
more features before 2.6.

{[[https://lists.gnupg.org/pipermail/gnupg-announce/2025q4/000499.html][Read more]]}

** GnuPG 2.5.13 and gpg4win 5.0.0-beta395 released (2025-10-22)

We are pleased to announce the availability of a new GnuPG release:
Version 2.5.13.  This release adds new features and fixes a couple of
bugs.

Along with this GnuPG version we also released a another beta
version of [[https://www.gpg4win.org/version5.html][Gpg4win 5.0]].

Note that this 2.5 series is fully supported and thus ready for
production use.  This means we won't break anything but may add some
more features before 2.6.

{[[https://lists.gnupg.org/pipermail/gnupg-announce/2025q4/000498.html][Read more]]}

** GnuPG 2.5.12 released (2025-09-02)

We are pleased to announce the availability of a new GnuPG release:
Version 2.5.12.  This release adds new features and fixes two
regressions.

Note that this 2.5 series is fully supported and thus ready for
production use.  This means we won't break anything but may add some
more features before 2.6.

{[[https://lists.gnupg.org/pipermail/gnupg-announce/2025q3/000497.html][Read more]]}

** New GnuPG merchandise available (2025-09-01)

We have launched a new web shop where you can [[https://gnupg.myspreadshop.de][find merchandise]] to show
your support for GnuPG. We have been planning to offer merchandise
again for a long time, and this print-on-demand service enables us to
offer a wide range of products, so we hope there is something for
everyone. Please contact us if you can't find what you're looking
for. You can get a 25% discount for orders within the next 9 days!

** GnuPG 2.5.9 with Debian packages released (2025-07-14)

We are pleased to announce the availability of a new GnuPG release.
Version 2.5.9 which will soon lead us to the new stable 2.6 series.
This release mostly fixes regression in the previous releases.  We now
also provide packages for [[https://debian.org][Debian]], [[https://devuan.org][Devuan]], and [[https://ubuntu.com][Ubuntu]] in addition to
the usual [[https://gpg4win.org/version5.html][Gpg4win]] beta installer.

{[[https://lists.gnupg.org/pipermail/gnupg-announce/2025q3/000495.html][Read more]]}

** GnuPG 2.5.8 released (2025-05-20)

We are pleased to announce the availability of a new GnuPG release:
version 2.5.8.  This release is another one in a series of public
testing releases eventually leading to a new stable version 2.6.  Do
not hesitate to use this new version; it is fully functional and
maintained.

{[[https://lists.gnupg.org/pipermail/gnupg-announce/2025q2/000494.html][Read more]]}


** GnuPG 2.5.6 and Gpg4win 5.0.0-Beta190 released (2025-05-09)

We are pleased to announce the availability of a new GnuPG release:
version 2.5.6.  This release is the third of a series of public
testing releases eventually leading to a new stable version 2.6.

Along with this GnuPG version we also released another *beta*
version of [[https://www.gpg4win.org/version5.html][Gpg4win 5.0]].

{[[https://lists.gnupg.org/pipermail/gnupg-announce/2025q2/000492.html][Read more]]}

** GnuPG 2.5.5 and Gpg4win 5.0.0-beta145 released (2025-03-10)

We are pleased to announce the availability of a new GnuPG release:
version 2.5.5.  This release fixes a couple of problems found in the
previous 2.5 versions.

Along with this GnuPG version we also released another beta version
of [[https://www.gpg4win.org/version5.html][Gpg4win 5.0]].

{[[https://lists.gnupg.org/pipermail/gnupg-announce/2025q1/000491.html][Read more]]}

** GnuPG 2.5.2 and Gpg4win 5.0.0-Beta32 released (2024-12-06)

We are pleased to announce the availability of a new GnuPG release:
version 2.5.2.  This release is the third of a series of public
testing releases eventually leading to a new stable version 2.6.

Along with this GnuPG version we also released a first *beta* version
of Gpg4win 5.0.

{[[https://lists.gnupg.org/pipermail/gnupg-announce/2024q4/000488.html][Read more]]}

** GnuPG 2.4.7 and Gpg4win 4.4.0 released (2024-11-27)

We are pleased to announce the availability of a new stable GnuPG
release: version 2.4.7.  This version fixes a couple of bugs.  Along
with this release we also released a new version of Gpg4win: version
4.4.0.

{[[https://lists.gnupg.org/pipermail/gnupg-announce/2024q4/000487.html][Read more]]}

** GnuPG 2.4.6 released (2024-10-29)

We are pleased to announce the availability of a new stable GnuPG
release: version 2.4.6.  This version fixes a couple of bugs, comes
with a few new features, and has now full support for Portuguese.

{[[https://lists.gnupg.org/pipermail/gnupg-announce/2024q4/000486.html][Read more]]}

** GnuPG 2.5.1 released with FIPS-203 support (2024-09-12)

We are pleased to announce the availability of a new GnuPG release:
version 2.5.1.  This release is the second of a series of public
testing releases eventually leading to a new stable version 2.6.

The main features in the 2.6 series are improvements for 64 bit
Windows and the introduction of a PQC encryption algorithm.

{[[https://lists.gnupg.org/pipermail/gnupg-announce/2024q3/000485.html][Read more]]}.

** Our FTP server has been discontinued  (2024-08-20)

For technical and organisational reasons we recently shutdown our FTP
server.  Instead of using ftp.gnupg.org please use
https://gnupg.org/ftp/ .

** GnuPG 2.5.0 released for public testing (2024-07-05)

We are pleased to announce the availability of a new GnuPG release:
version 2.5.0.  This release is the first of a series of public testing
releases eventually leading to a new stable version 2.6.

The main features in the 2.6 series are improvements for 64 bit
Windows and the introduction of a PQC encryption algorithm.

{[[https://lists.gnupg.org/pipermail/gnupg-announce/2024q3/000484.html][Read more]]}.


** Libgcrypt 1.11 is the new stable branch (2024-06-19)

Although we will keep on maintaining the 1.8 and 1.10 branch for some
more time, the new stable branch is now 1.11.  Version 1.11.0 comes
with a lot of performance improvements, new interfaces, and now
supports common quantum-resistant algorithms.  It provides full API
and ABI compatibility to previous versions.  {[[https://lists.gnupg.org/pipermail/gnupg-announce/2024q2/000483.html][more]]}

** GnuPG 2.4.5 and Gpg4win 4.3.1 released (2024-03-12)

We are pleased to announce the availability of a new stable GnuPG
release: version 2.4.5. This version fixes a couple of bugs and comes
with some new features.  {[[https://lists.gnupg.org/pipermail/gnupg-announce/2024q1/000482.html][more]]}

** Security advisory for smartcard keys with backup               :important:

GnuPG versions 2.4.2, 2.4.3, and 2.2.42 had a regression in the
default way to create smartcard keys.  If you created a key with the
/--edit-key/ command using one of these versions, please head over to
our security advisory:

 https://gnupg.org/blog/20240125-smartcard-backup-key.html

** GnuPG 2.4.4 released (2024-01-25)

We are pleased to announce the availability of a new stable GnuPG
release: version 2.4.4. This version fixes a couple of bugs, comes
with some new features.  A smartcard related security bug is also
fixed and a tool to check for this flaw is provided.  {[[https://lists.gnupg.org/pipermail/gnupg-announce/2024q1/000481.html][more]]}


** </div><!-- end pure-g -->                                   :html:virtual:


* COMMENT
This is the publishing info used for the GnuPG pages
#+begin_src emacs-lisp
  (progn
   (setq gpgweb-root-dir (file-name-directory (buffer-file-name)))
   (setq gpgweb-stage-dir (concat gpgweb-root-dir "../stage"))
   (require 'gpgweb (concat gpgweb-root-dir "share/gpgweb.el"))
   (setq org-publish-use-timestamps-flag nil)
   (setq org-export-html-toplevel-hlevel 1)
   (setq org-export-html-coding-system 'utf-8)
   (gpgweb-setup-project))
#+end_src
