#+TITLE: The GNU Privacy Guard
#+STARTUP: showall
#+SETUPFILE: "share/setup.inc"
#+GPGWEB-NEED-SWDB
#+HTML_HEAD_EXTRA: <link type="application/rss+xml" href="https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg-doc.git;a=rss;f=web/index.org"/>
#+HTML_HEAD_EXTRA: <link rel="stylesheet" href="/share/pure-min.css.gz" type="text/css" />
#+HTML_HEAD_EXTRA: <link rel="stylesheet" href="/share/grids-responsive-min.css.gz" type="text/css" />

* The GNU Privacy Guard
#+index: GnuPG
#+index: GPG
#+index: PGP
#+index: Gpg4win

GnuPG is a complete and free implementation of the OpenPGP standard as
defined by [[https://www.ietf.org/rfc/rfc4880.txt][RFC4880]] (also known as /PGP/). GnuPG allows you to encrypt and
sign your data and communications; it features a versatile key management
system, along with access modules for all kinds of public key
directories.  GnuPG, also known as /GPG/, is a command line tool with
features for easy integration with other applications.  A wealth of
[[file:software/frontends.html][frontend applications]] and [[file:software/libraries.html][libraries]] are available.  GnuPG also
provides support for S/MIME and Secure Shell (ssh).

Since its introduction in 1997, GnuPG is [[https://www.gnu.org/philosophy/free-sw.html][Free Software]] (meaning that
it respects your freedom). It can be freely used, modified and
distributed under the terms of the [[https://www.gnu.org/copyleft/gpl.html][GNU General Public License]] .

The current version of GnuPG is {{{gnupg24_ver}}}.  See the [[file:download/index.org][download]]
page for other maintained versions.

[[https://www.gpg4win.org][Gpg4win]] is a Windows version of GnuPG featuring a context menu tool, a
crypto manager, and an Outlook plugin to send and receive standard
PGP/MIME mails.  The current version of Gpg4win is {{{gpg4win_ver}}}.

** <div class="pure-g">                                        :html:virtual:



* Reconquer your privacy
   :PROPERTIES:
   :HTML_CONTAINER_CLASS: pure-u-1 pure-u-md-1-2
   :END:

#+begin_quote
Arguing that you don't care about the right to privacy
because you have nothing to hide is no different from
saying you don't care about free speech because you have
nothing to say.   \ndash\nbsp{}Edward\nbsp{}Snowden
#+end_quote

Using encryption helps to protect your privacy and the privacy of the
people you communicate with.  Encryption makes life difficult for bulk
surveillance systems.  GnuPG is one of the tools that Snowden used to
uncover the secrets of the NSA.

Please visit the [[https://emailselfdefense.fsf.org][Email Self-Defense]] site to learn how and why you
should use GnuPG for your electronic communication.


* News
   :PROPERTIES:
   :HTML_CONTAINER_CLASS: pure-u-1 pure-u-md-1-2
   :END:
#+index: News

The latest blog entries:
#+begin_html
<ul>
<!--INSERT-BLOG-HEADLINE-->
</ul>
#+end_html

The latest release news:\\
([[file:news.org][all news]])

# For those of you who like reading world’s news with an RSS reader,
# GnuPG's latest news are available as [[http://feedvalidator.org/check.cgi?url%3Dhttps://www.gnupg.org/news.en.rss][RSS 2.0 compliant]] feed.  Just
# point or paste the [[news.en.rss][RSS file]] into your aggregator.

** GnuPG 2.4.3 released (2023-07-04)

We are pleased to announce the availability of a new stable GnuPG
release: version 2.4.3.  This version fixes some minor bugs and
improves the performance on Windows. {[[https://lists.gnupg.org/pipermail/gnupg-announce/2023q3/000480.html][more]]}

** GnuPG 2.4.2 released (2023-05-30)

We are pleased to announce the availability of a new stable GnuPG
release: version 2.4.2.  This version fixes some minor bugs and
improves the performance on Windows. {[[https://lists.gnupg.org/pipermail/gnupg-announce/2023q2/000479.html][more]]}

** GnuPG 2.4.1 released (2023-04-28)

We are pleased to announce the availability of a new stable GnuPG
release: version 2.4.1.  This release comes with a lot of new features
and fixes some minor bugs. {[[https://lists.gnupg.org/pipermail/gnupg-announce/2023q2/000478.html][more]]}

** 25 Years of GnuPG (2022-12-20)

Exactly 25 years ago the very first release of GnuPG was published.
We are pleased to take this opportunity to announce the availability
of GnuPG version 2.4.0.

This release has a few new features and the binary releases come with
an updated Libksba to fix another vulnerability related to
CVE-2022-3515.  {[[https://lists.gnupg.org/pipermail/gnupg-announce/2022q4/000477.html][more]]}


** Libksba security advisory update (2022-12-20)                  :important:

Another bug has been found in [[https://gnupg.org/software/libksba/][Libksba]] which affects all versions of
libksba before 1.6.3 ({{{CVE(2022-47629)}}}).  Our [[https://gnupg.org/blog/20221017-pepe-left-the-ksba.html][security advisory]]
for {{{CVE(2022-3512)}}} has been updated accordingly.  Windows users
should update to [[https://files.gpg4win.org/gpg4win-4.1.0.exe][Gpg4win 4.1.0]] or to GnuPG\nbsp{}VS-Desktop 3.1.26.

** GnuPG / Libksba security advisory (2022-10-17)                 :important:

A severe bug has been found in [[https://gnupg.org/software/libksba/][Libksba]], the library used by GnuPG for
parsing the ASN.1 structures as used by S/MIME.  The bug affects all
versions of Libksba before 1.6.2 and may be used for remote code
execution.  *Updating this library is thus important*.

Please see our [[https://gnupg.org/blog/20221017-pepe-left-the-ksba.html][security advisory]] for {{{CVE(2022-3512)}}}. For
download links please see the [[file:download/index.org][download]] page.  Windows users should
update to [[https://files.gpg4win.org/gpg4win-4.0.4.exe][Gpg4win 4.0.4]] or to GnuPG\nbsp{}VS-Desktop 3.1.25.


** GnuPG 2.3.8 released (2022-10-13)

We are pleased to announce the availability of a new stable GnuPG
release: version 2.3.8.  This release comes with a lot of new features
and the binary releases come with the fix for the Libksba
vulnerability {{{CVE(2022-3515)}}}.  {[[https://lists.gnupg.org/pipermail/gnupg-announce/2022q4/000476.html][more]]}

** GnuPG 2.3.7 released (2022-07-11)

We are pleased to announce the availability of a new stable GnuPG
release: version 2.3.7.  This release fixes {{{CVE(2022-34903)}}} which could
be used to inject wrong status information in signatures.  The status
information could then be abused to display a wrong validity in
Kleopatra and other users of GPGME.  {[[https://lists.gnupg.org/pipermail/gnupg-announce/2022q3/000474.html][more]]}

** GnuPG 2.3.6 released (2022-04-25)

We are pleased to announce the availability of a new stable GnuPG
release: version 2.3.6. This release fixes a regression introduced in
2.3.5 released just a few days ago.  {[[https://lists.gnupg.org/pipermail/gnupg-announce/2022q2/000473.html][more]]}

** GnuPG 2.3.5 released (2022-04-21)

We are pleased to announce the availability of a new *stable GnuPG*
release: version 2.3.5. This is another release in the stable 2.3
series which introduces new options, improves the performance, and
fixes some bugs. {[[https://lists.gnupg.org/pipermail/gnupg-announce/2022q2/000472.html][more]]}

** Libgcrypt 1.10 is the new stable branch (2022-03-28)

Although we will keep on maintaining the 1.8 branch, the new stable
branch is now 1.10.  Version 1.10.1 comes with a lot of performance
improvements and a few other new features.  It provides full API and
ABI compatibility to previous versions.  {[[https://lists.gnupg.org/pipermail/gnupg-announce/2022q1/000471.html][more]]}

** </div><!-- end pure-g -->                                   :html:virtual:


* COMMENT
This is the publishing info used for the GnuPG pages
#+begin_src emacs-lisp
  (progn
   (setq gpgweb-root-dir (file-name-directory (buffer-file-name)))
   (setq gpgweb-stage-dir (concat gpgweb-root-dir "../stage"))
   (require 'gpgweb (concat gpgweb-root-dir "share/gpgweb.el"))
   (setq org-publish-use-timestamps-flag nil)
   (setq org-export-html-toplevel-hlevel 1)
   (setq org-export-html-coding-system 'utf-8)
   (gpgweb-setup-project))
#+end_src
