#+TITLE: The GNU Privacy Guard
#+STARTUP: showall
#+SETUPFILE: "share/setup.inc"
#+GPGWEB-NEED-SWDB

* The GNU Privacy Guard
#+index: GnuPG
#+index: GPG
#+index: PGP
#+index: Gpg4win

GnuPG is a complete and free implementation of the OpenPGP standard as
defined by [[https://www.ietf.org/rfc/rfc4880.txt][RFC4880]] (also known as /PGP/). GnuPG allows to encrypt and
sign your data and communication, features a versatile key management
system as well as access modules for all kinds of public key
directories.  GnuPG, also known as /GPG/, is a command line tool with
features for easy integration with other applications. A wealth of
[[file:software/frontends.html][frontend applications]] and [[file:software/libraries.html][libraries]] are available.  GnuPG also
provides support for S/MIME and Secure Shell (ssh).

GnuPG is [[https://www.gnu.org/philosophy/free-sw.html][Free Software]] (meaning that it respects your freedom). It can
be freely used, modified and distributed under the terms of the
[[https://www.gnu.org/copyleft/gpl.html][GNU General Public License]] .

The current version of GnuPG is {{{gnupg21_ver}}}.  See the [[file:download/index.org][download]]
page for other maintained versions.

[[https://www.gpg4win.org][Gpg4win]] provides a Windows version of the older GnuPG 2.0 branch.  It
is nicely integrated into an installer and features several frontends
as well as English and German manuals.


* Reconquer your privacy

#+begin_quote
Arguing that you don't care about the right to privacy
because you have nothing to hide is no different from
saying you don't care about free speech because you have
nothing to say.   \ndash\nbsp{}Edward\nbsp{}Snowden
#+end_quote

Using encryption helps to protect your privacy and the privacy of the
people you communicate with.  Encryption makes life difficult for bulk
surveillance systems.  GnuPG is one of the tools that Snowden used to
uncover the secrets of the NSA.

Please visit the [[https://emailselfdefense.fsf.org][Email Self-Defense]] site to learn how and why you
should use GnuPG for your electronic communication.  If you need
printed leaflets check out [[https://fsfe.org/contribute/spreadtheword.html#gnupg-leaflet][FSFE’s GnuPG leaflet]].


* News
#+index: News

The latest blog entries:
#+begin_html
<ul>
<!--INSERT-BLOG-HEADLINE-->
</ul>
#+end_html

The latest release news:\\
([[file:news.org][all news]])

# For those of you who like reading world’s news with an RSS reader,
# GnuPG's latest news are available as [[http://feedvalidator.org/check.cgi?url%3Dhttps://www.gnupg.org/news.en.rss][RSS 2.0 compliant]] feed.  Just
# point or paste the [[news.en.rss][RSS file]] into your aggregator.

** GnuPG 2.1.21 released (2017-05-15)                             :important:

A new version of GnuPG has been released.  This release fixes a
pubring.gpg corruption bug introduced with 2.1.20.  Read the full
[[https://lists.gnupg.org/pipermail/gnupg-announce/2017q2/000405.html][announcement mail]] for details.

** GnuPG 2.1.20 released (2017-04-03)

A new version of GnuPG has been released.  Read the full [[https://lists.gnupg.org/pipermail/gnupg-announce/2017q2/000404.html][announcement
mail]] for details.

** New installer for GnuPG 2.1.19 (2017-03-28)

An updated Windows [[https://gnupg.org/ftp/gcrypt/binary/gnupg-w32-2.1.19_20170328.exe][installer]] for GnuPG 2.1.19 is now available.  This
installer fixes problems retrieving keys for [[https://posteo.de][Posteo]] accounts and other
servers with limited set of TLS algorithms.

** GnuPG Made Easy 1.9.0 released (2017-03-28)

[[file:software/gpgme/index.org][GPGME]] is a library that allows to add support for cryptography to a
program.  {[[https://lists.gnupg.org/pipermail/gnupg-announce/2017q1/000403.html][more]]}


** GnuPG 2.1.19 released (2017-03-01)

A new version of GnuPG has been released.  Read the full [[https://lists.gnupg.org/pipermail/gnupg-announce/2017q1/000402.html][announcement
mail]] for details.

** GnuPG 2.1.18 released (2017-01-23)

A new version of GnuPG has been released.  Read the full [[https://lists.gnupg.org/pipermail/gnupg-announce/2017q1/000401.html][announcement
mail]] for details.

** Libgcrypt 1.7.6 released (2017-01-18)

We are pleased to announce the availability of Libgcrypt version
1.7.6.  This is a maintenance release for the stable version of
[[file:software/libgcrypt/index.org][Libgcrypt]] with a few bug fixes.

** GnuPG 2.1.17 released (2016-12-20)

A new version of GnuPG has been released.  Read the full [[https://lists.gnupg.org/pipermail/gnupg-announce/2016q4/000400.html][announcement
mail]] for details.

** Libgcrypt 1.7.5 released (2016-12-15)

We are pleased to announce the availability of Libgcrypt version
1.7.5.  This is a maintenance release for the stable version of
[[file:software/libgcrypt/index.org][Libgcrypt]] with a few bug fixes. [[https://lists.gnupg.org/pipermail/gnupg-announce/2016q4/000399.html][{more}]]

** Pinentry 1.0.0 released (2016-11-22)

After 14 years is was time to bump up the version of [[file:software/pinentry/index.org][Pinentry]] to 1.0.
This new release fixes a couple of minor bugs and introduces features
to better diagnose problems.  See the [[../../download/index.org::pinentry][download]] section on how to get
Pinentry.

** GPA 0.9.10 released (2016-11-19)

A maintenance release of the [[file:software/gpa/index.org][GNU Privacy Assistant]] is now available.
Note that some of the changes are only available when build with the
latest [[file:software/gpgme/index.org][GPGME]] version and used with GnuPG 2.1.16 or later.

** GnuPG 2.1.16 released (2016-11-18)

It has been 3 months since the last GnuPG /modern/ release and thus it
was time for a new one: Version 2.1.16 is now available.  Read the
full [[https://lists.gnupg.org/pipermail/gnupg-announce/2016q4/000398.html][announcement mail]] for details.

** GnuPG Made Easy (GPGME) 1.7.0 released (2016-09-21)

[[file:software/gpgme/index.org][GPGME]] is a library that allows to add support for cryptography to a
program.  Highlights in this release are Python and C++ language
bindings as well as support for GnuPG 2.1 features.  {[[https://lists.gnupg.org/pipermail/gnupg-announce/2016q3/000397.html][more]]}

** GnuPG 2.1.15 released (2016-08-18)

A new version of the /modern/ branch of GnuPG has been released.
Read the full [[https://lists.gnupg.org/pipermail/gnupg-announce/2016q3/000396.html][announcement mail]] for details.

** Security fixes for Libgcrypt and GnuPG 1.4 (2016-08-17)        :important:

A bug in the random number generator of Libgcrypt and in GnuPG 1.4 has
been found.  Updating the software is highly suggested.  Please read
this [[https://lists.gnupg.org/pipermail/gnupg-announce/2016q3/000395.html][mail]] for details.  Note that the CVE id in that mail is not
correct, the correct one is CVE-2016-6313.


* A big Thanks to all supporters

Due to this [[http://www.propublica.org/article/the-worlds-email-encryption-software-relies-on-one-guy-who-is-going-broke][ProPublica article]] we received more than 120,000 \euro of
individual donations on a single day.  There was even more: The [[https://www.linuxfoundation.org/programs/core-infrastructure-initiative][Core
Infrastructure Initiative]] granted 60,000 $ for 2015.  Our payment
service [[https://twitter.com/stripe/status/563449352635432960][Stripe]] and [[https://www.facebook.com/notes/protect-the-graph/supporting-gnu-privacy-guard/1564591893780956][Facebook]] will each give 50,000 $ to the project.
And finally the [[https://www.wauland.de/en/donation.html#61][Wau Holland Stiftung]] is collecting tax deductible
funds for GnuPG (19000 \euro plus 57 BTC).

As the main author of GnuPG, I like to thank everyone for supporting
the project, be it small or large individual donations, helping users,
providing corporate sponsorship, working on the software, and for all
the encouraging words.

GnuPG does not stand alone: there are many other projects, often
unknown to most people, which are essential to keep the free Internet
running.  Many of them are run by volunteers who spend a lot of unpaid
time on them.  They need our support as well.

/--- Werner, 2015-02-06/

(see also this [[https://gnupg.org/blog/20150310-gnupg-in-february.html][blog]] entry)

* COMMENT
This is the publishing info used for the GnuPG pages
#+begin_src emacs-lisp
  (progn
   (setq gpgweb-root-dir (file-name-directory (buffer-file-name)))
   (setq gpgweb-stage-dir (concat gpgweb-root-dir "../stage"))
   (require 'gpgweb (concat gpgweb-root-dir "share/gpgweb.el"))
   (setq org-publish-use-timestamps-flag nil)
   (setq org-export-html-toplevel-hlevel 1)
   (setq org-export-html-coding-system 'utf-8)
   (gpgweb-setup-project))
#+end_src
