#+TITLE: The GNU Privacy Guard
#+STARTUP: showall
#+SETUPFILE: "share/setup.inc"

* The GNU Privacy Guard
#+index: GnuPG
#+index: GPG
#+index: Gpg4win
#+index: GPGTools

GnuPG is the [[http://www.gnu.org/][GNU project]]'s complete and free implementation of the
OpenPGP standard as defined by [[http://www.ietf.org/rfc/rfc4880.txt][RFC4880]]. GnuPG allows to encrypt and
sign your data and communication, features a versatile key management
system as well as access modules for all kinds of public key
directories. GnuPG, also known as /GPG/, is a command line tool with
features for easy integration with other applications. A wealth of
[[file:related_software/frontends.html][frontend applications]] and [[file:related_software/libraries.html][libraries]] are available. Version 2 of GnuPG
also provides support for S/MIME.

GnuPG is [[http://www.gnu.org/philosophy/free-sw.html][Free Software]] (meaning that it respects your freedom). It can
be freely used, modified and distributed under the terms of the
[[http://www.gnu.org/copyleft/gpl.html][GNU General Public License]] .

GnuPG comes in two flavours: [[download][{{{gnupg1_ver}}}]] is the well known and
portable standalone version, whereas [[download][{{{gnupg_ver}}}]] is the enhanced
and somewhat harder to build version.

Project [[http://www.gpg4win.org][Gpg4win]] provides a Windows version of GnuPG. It is nicely
integrated into an installer and features several frontends as well as
English and German manuals.

Project [[http://gpgtools.org][GPGTools]] provides a Mac OS X version of GnuPG. It is nicely
integrated into an installer and features all required tools.

Project [[https://www.gnupg.org/aegypten/][Aegypten]] developed the S/MIME functionality in GnuPG 2.

* Latest news
#+index: News

The following frames report the latest news from GnuPG.  A list with
all [[file:news.org][news of previous years]] is also available.

# For those of you who like reading world’s news with an RSS reader,
# GnuPG's latest news are available as [[http://feedvalidator.org/check.cgi?url%3Dhttps://www.gnupg.org/news.en.rss][RSS 2.0 compliant]] feed.  Just
# point or paste the [[news.en.rss][RSS file]] into your aggregator.

** Goteo campaign: preliminary results (2014-05-12)

The blog has a report on the current status of the campaign including
an overview of the financial results.  [[https://www.gnupg.org/blog/20140512-rewards-sent.html][{read here}]]

** Mission complete: campaign ends, closing stats (2014-02-06)

After 50 days of crowdfunding, the GnuPG campaign for new website and
infrastructure will close tomorrow. That means rewards for backers can
now be ordered and preparations for dispatch can begin. Here are the
results so far.  [[https://www.gnupg.org/blog/20140206-crowdfunding-complete.html][{more}]]


** 16 Years of protecting privacy (2013-12-20)

Today marks 16 years since the first release of GnuPG. In that time
the project has grown from being a hacker’s hobby into one of the
world’s most critical anti-surveillance tools.  Today GnuPG stands at
the front line of the battle between invasive surveillance and civil
liberties.  [[https://www.gnupg.org/blog/20131220-gnupg-turned-0x10.html][{more}]]

** GnuPG launches crowdfunding campaign (2013-12-19)

Today GNU Privacy Guard (GnuPG) has launched its first
[[http://goteo.org/project/gnupg-new-website-and-infrastructure][crowdfunding campaign]] with the aim of building a new website and long term
infrastructure.  [[http://lists.gnupg.org/pipermail/gnupg-announce/2013q4/000338.html][{more}]] [[https://www.gnupg.org/blog/20131219-gnupg-launches-crowfunding.de.html][{deutsch}]] [[https://www.gnupg.org/blog/20131219-gnupg-launches-crowfunding.fr.html][{francaise}]]

** GnuPG 1.4.16 released (2013-12-18)                             :important:

Along with the publication of an interesting new [[http://www.cs.tau.ac.il/~tromer/acoustic/][side channel attack]]
by Genkin, Shamir, and Tromer we announce the availability of a new
stable GnuPG release to relieve this bug: Version 1.4.16 ...  [[http://lists.gnupg.org/pipermail/gnupg-announce/2013q4/000337.html][{more}]]



* COMMENT
This is the publishing info used for the GnuPG pages
#+begin_src emacs-lisp
  (progn
   (setq gpgweb-root-dir (file-name-directory (buffer-file-name)))
   (require 'gpgweb (concat gpgweb-root-dir "share/gpgweb.el"))
   (setq org-export-html-toplevel-hlevel 1)
   (setq org-export-html-coding-system 'utf-8)
   (gpgweb-setup-project))
#+end_src
