#+TITLE: The GNU Privacy Guard
#+STARTUP: showall
#+SETUPFILE: "share/setup.inc"
#+GPGWEB-NEED-SWDB

* The GNU Privacy Guard
#+index: GnuPG
#+index: GPG
#+index: PGP
#+index: Gpg4win

GnuPG is a complete and free implementation of the OpenPGP standard as
defined by [[https://www.ietf.org/rfc/rfc4880.txt][RFC4880]] (also known as /PGP/). GnuPG allows you to encrypt and
sign your data and communications; it features a versatile key management
system, along with access modules for all kinds of public key
directories.  GnuPG, also known as /GPG/, is a command line tool with
features for easy integration with other applications.  A wealth of
[[file:software/frontends.html][frontend applications]] and [[file:software/libraries.html][libraries]] are available.  GnuPG also
provides support for S/MIME and Secure Shell (ssh).

Since its introduction in 1997, GnuPG is [[https://www.gnu.org/philosophy/free-sw.html][Free Software]] (meaning that
it respects your freedom). It can be freely used, modified and
distributed under the terms of the [[https://www.gnu.org/copyleft/gpl.html][GNU General Public License]] .

The current version of GnuPG is {{{gnupg22_ver}}}.  See the [[file:download/index.org][download]]
page for other maintained versions.

[[https://www.gpg4win.org][Gpg4win]] is a Windows version of GnuPG featuring a context menu tool, a
crypto manager, and an Outlook plugin to send and receive standard
PGP/MIME mails.  The current version of Gpg4win is {{{gpg4win_ver}}}.

* Reconquer your privacy

#+begin_quote
Arguing that you don't care about the right to privacy
because you have nothing to hide is no different from
saying you don't care about free speech because you have
nothing to say.   \ndash\nbsp{}Edward\nbsp{}Snowden
#+end_quote

Using encryption helps to protect your privacy and the privacy of the
people you communicate with.  Encryption makes life difficult for bulk
surveillance systems.  GnuPG is one of the tools that Snowden used to
uncover the secrets of the NSA.

Please visit the [[https://emailselfdefense.fsf.org][Email Self-Defense]] site to learn how and why you
should use GnuPG for your electronic communication.


* News
#+index: News

The latest blog entries:
#+begin_html
<ul>
<!--INSERT-BLOG-HEADLINE-->
</ul>
#+end_html

The latest release news:\\
([[file:news.org][all news]])

# For those of you who like reading world’s news with an RSS reader,
# GnuPG's latest news are available as [[http://feedvalidator.org/check.cgi?url%3Dhttps://www.gnupg.org/news.en.rss][RSS 2.0 compliant]] feed.  Just
# point or paste the [[news.en.rss][RSS file]] into your aggregator.

** GnuPG 2.2.13 released (2019-02-12)

We are pleased to announce the availability of GnuPG version 2.2.13.
This is a maintenance release fixing a few problems and adding some
minor features. {[[https://lists.gnupg.org/pipermail/gnupg-announce/2019q1/000434.html][more]]}

** GnuPG 2.2.12 released (2018-12-14)

We are pleased to announce the availability of GnuPG version 2.2.12.
This is a maintenance release fixing a few problems and adding some
minor features. {[[https://lists.gnupg.org/pipermail/gnupg-announce/2018q4/000433.html][more]]}

** GnuPG 2.2.11 released (2018-11-06)

We are pleased to announce the availability of GnuPG version 2.2.11.
This is a maintenance release fixing a few problems. {[[https://lists.gnupg.org/pipermail/gnupg-announce/2018q4/000432.html][more]]}

** GnuPG Made Easy 1.12.0 released (2018-10-08)

[[file:software/gpgme/index.org][GPGME]] is a library that allows to add support for cryptography to a
program. {[[https://lists.gnupg.org/pipermail/gnupg-announce/2018q4/000429.html][more]]}.

** GnuPG 2.2.10 released (2018-08-30)

We are pleased to announce the availability of GnuPG version 2.2.10.
This is a maintenance release fixing a few problems. {[[https://lists.gnupg.org/pipermail/gnupg-announce/2018q3/000428.html][more]]}

** GnuPG 2.2.9 released (2018-07-12)

We are pleased to announce the availability of GnuPG version 2.2.9.
This is a maintenance release fixing a few problems. {[[https://lists.gnupg.org/pipermail/gnupg-announce/2018q3/000427.html][more]]}

** Libgcrypt 1.8.3 released (2018-06-13)

We are pleased to announce the availability of [[file:software/libgcrypt/index.org][Libgcrypt]] version 1.8.3
and 1.7.10.  These releases fix a local side-channel attack on ECDSA
signature as described in the white pager “Return of the Hidden Number
Problem” and got assigned {{{CVE(2018-0495)}}}.  {[[https://lists.gnupg.org/pipermail/gnupg-announce/2018q2/000426.html][more]]}

** GnuPG 1.4.23 released (2018-06-11)                             :important:

Although GnuPG 1.4 is of very limited use today we did a maintenance
release to address the critical security bug {{{CVE(2017-7526)}}}.
See the [[../../download/index.org][download]] section on how to get this version.

** GnuPG 2.2.8 released (2018-06-08)                              :important:

This version fixes a critical security bug.  Either this version or a
vendor provided fix should be installed.  There are also a few other
changes; see the [[https://lists.gnupg.org/pipermail/gnupg-announce/2018q2/000425.html][announcement]] mail.  This is {{{CVE(2018-12020)}}} and
our bug [[https://dev.gnupg.org/T4012][#4012]].

* COMMENT
This is the publishing info used for the GnuPG pages
#+begin_src emacs-lisp
  (progn
   (setq gpgweb-root-dir (file-name-directory (buffer-file-name)))
   (setq gpgweb-stage-dir (concat gpgweb-root-dir "../stage"))
   (require 'gpgweb (concat gpgweb-root-dir "share/gpgweb.el"))
   (setq org-publish-use-timestamps-flag nil)
   (setq org-export-html-toplevel-hlevel 1)
   (setq org-export-html-coding-system 'utf-8)
   (gpgweb-setup-project))
#+end_src
