#+TITLE: The GNU Privacy Guard
#+STARTUP: showall
#+SETUPFILE: "share/setup.inc"


* Securing the future of GnuPG

Work on GnuPG is mostly financed from donations.  To continue
maintaining GnuPG so to keep it strong and secure against the ever
increasing mass surveillance we need your support.  Until the end of
November we received a total of 6584\thinsp\euro (~5500 net) donations
for this year.  Along with the 18000\thinsp\euro net from the [[https://www.gnupg.org/blog/20140512-rewards-sent.html][Goteo
campaign]] this paid for less than 50% of the costs for one
developer.

#+BEGIN_HTML
<div class="donation-progress">
  <div class="donation-progress-bar"
style="width: 0%"><!--REPLACE-PROGRESS-PERCENT-->
<p>&nbsp;</p></div>
  <p><span style="float: left">
<!--INSERT-PROGRESS-LEFT-->
  </span>
  <span style="float: right">
<!--INSERT-PROGRESS-RIGHT-->
  </span>
</div>
<p class="doclear" style="clear: both"></p>
#+END_HTML

For a critical project of this size two experienced developers are
required for proper operation.  This requires gross revenues of 120000
Euro per year.  Unfortunately there is currently only one underpaid
full time developer who is barely able to keep up with the work; see
this [[file:blog/20141214-gnupg-and-g10.org][blog entry]] for some backgound.  Please help to secure the
future of GnuPG and consider to [[file:donate/index.org][donate]] to this project [[file:donate/index.org][now]].


* The GNU Privacy Guard
#+index: GnuPG
#+index: GPG
#+index: PGP
#+index: Gpg4win

GnuPG is a complete and free implementation of the OpenPGP standard as
defined by [[http://www.ietf.org/rfc/rfc4880.txt][RFC4880]] (also known as /PGP/). GnuPG allows to encrypt and
sign your data and communication, features a versatile key management
system as well as access modules for all kinds of public key
directories. GnuPG, also known as /GPG/, is a command line tool with
features for easy integration with other applications. A wealth of
[[file:related_software/frontends.html][frontend applications]] and [[file:related_software/libraries.html][libraries]] are available. Version 2 of GnuPG
also provides support for S/MIME and Secure Shell (ssh).

GnuPG is [[http://www.gnu.org/philosophy/free-sw.html][Free Software]] (meaning that it respects your freedom). It can
be freely used, modified and distributed under the terms of the
[[http://www.gnu.org/copyleft/gpl.html][GNU General Public License]] .

GnuPG comes in three flavours:

 - {{{gnupg_ver}}} is the /stable/ version suggested for most users,

 - {{{gnupg21_ver}}} is the brand-new /modern/ version with support
   for [[https://en.wikipedia.org/wiki/Elliptic_curve_cryptography][ECC]] and many other new features,

 - and {{{gnupg1_ver}}} is the /classic/ portable version.

Project [[http://www.gpg4win.org][Gpg4win]] provides a Windows version of GnuPG /stable/. It is
nicely integrated into an installer and features several frontends as
well as English and German manuals.

* Reconquer your privacy

Even if you have nothing to hide, using encryption helps protect the
privacy of people you communicate with, and makes life difficult for
bulk surveillance systems. If you do have something important to hide,
you are in good company; GnuPG is one of the tools that Edward Snowden
used to uncover his secrets about the NSA.

Please visit the [[https://emailselfdefense.fsf.org][Email Self-Defense]] site to learn how and why you
should use GnuPG for your electronic communication.

* Latest news
#+index: News

The following frames report the latest news from GnuPG.  A list with
all [[file:news.org][news of previous years]] is also available.

# For those of you who like reading world’s news with an RSS reader,
# GnuPG's latest news are available as [[http://feedvalidator.org/check.cgi?url%3Dhttps://www.gnupg.org/news.en.rss][RSS 2.0 compliant]] feed.  Just
# point or paste the [[news.en.rss][RSS file]] into your aggregator.

** GnuPG 2.1.1 released (2014-12-16)

This is the second release of the /modern/ branch of GnuPG.  It fixes
a lot of bugs and brings some new features.  Read more about 2.1 at
the [[file:faq/whats-new-in-2.1.org][feature overview]] page and in the [[http://lists.gnupg.org/pipermail/gnupg-announce/2014q4/000360.html][announcement]] mail.


** Libksba 1.3.2 released (2014-11-25)                            :important:

This is a security fix release and all users of Libksba should update
to this version.  Note that *GnuPG 2.x* makes use of Libksba and thus
all user of GnuPG 2.x need to install this new version of Libksba and
restart the dirmngr process.  Read the full [[http://lists.gnupg.org/pipermail/gnupg-announce/2014q4/000359.html][announcement]].


** GnuPG 2.1.0 with ECC support released (2014-11-06)

This is the first released of the new /modern/ branch of GnuPG.  It
features a lot of new things including support for ECC.  Read more at
the [[file:faq/whats-new-in-2.1.org][feature overview]] page and in the [[http://lists.gnupg.org/pipermail/gnupg-announce/2014q4/000358.html][announcement]] mail.



* COMMENT
This is the publishing info used for the GnuPG pages
#+begin_src emacs-lisp
  (progn
   (setq gpgweb-root-dir (file-name-directory (buffer-file-name)))
   (require 'gpgweb (concat gpgweb-root-dir "share/gpgweb.el"))
   (setq org-publish-use-timestamps-flag nil)
   (setq org-export-html-toplevel-hlevel 1)
   (setq org-export-html-coding-system 'utf-8)
   (gpgweb-setup-project))
#+end_src
