#+TITLE: The GNU Privacy Guard
#+STARTUP: showall
#+SETUPFILE: "share/setup.inc"

* The GNU Privacy Guard
#+index: GnuPG
#+index: GPG
#+index: Gpg4win
#+index: GPGTools

GnuPG is the [[http://www.gnu.org/][GNU project]]'s complete and free implementation of the
OpenPGP standard as defined by [[http://www.ietf.org/rfc/rfc4880.txt][RFC4880]]. GnuPG allows to encrypt and
sign your data and communication, features a versatile key management
system as well as access modules for all kinds of public key
directories. GnuPG, also known as /GPG/, is a command line tool with
features for easy integration with other applications. A wealth of
[[file:related_software/frontends.html][frontend applications]] and [[file:related_software/libraries.html][libraries]] are available. Version 2 of GnuPG
also provides support for S/MIME.

GnuPG is [[http://www.gnu.org/philosophy/free-sw.html][Free Software]] (meaning that it respects your freedom). It can
be freely used, modified and distributed under the terms of the [[http://www.gnu.org/copyleft/gpl.html][GNU
General Public License]] .

GnuPG comes in two flavours: [[download][{{{gnupg1_ver}}}]] is the well known and
portable standalone version, whereas [[download][{{{gnupg_ver}}}]] is the enhanced
and somewhat harder to build version.

Project [[http://www.gpg4win.org][Gpg4win]] provides a Windows version of GnuPG. It is nicely
integrated into an installer and features several frontends as well as
English and German manuals.

Project [[http://gpgtools.org][GPGTools]] provides a Mac OS X version of GnuPG. It is nicely
integrated into an installer and features all required tools.

Project [[http://www.gnupg.org/aegypten/][Aegypten]] developed the S/MIME functionality in GnuPG 2.

* Latest news
#+index: News

The following frames report the latest news from GnuPG.  A list with
all [[file:news.org][news of previous years]] is also available.

# For those of you who like reading world’s news with an RSS reader,
# GnuPG's latest news are available as [[http://feedvalidator.org/check.cgi?url%3Dhttp://www.gnupg.org/news.en.rss][RSS 2.0 compliant]] feed.  Just
# point or paste the [[news.en.rss][RSS file]] into your aggregator.

** Blog: Getting Goteo crowdfunding approval (2013-12-18)

The targets are set, the rewards are prepared, the press release has
been edited and translated, and now we're waiting for approval from
the crowdfunding platform Goteo ...  [[http://blog.gnupg.org/20131218-getting-goteo-approval.html][{more}]]

** GnuPG 1.4.16 released (2013-12-18)                             :important:

Along with the publication of an interesting new [[http://www.cs.tau.ac.il/~tromer/acoustic/][side channel attack]]
by Genkin, Shamir, and Tromer we announce the availability of a new
stable GnuPG release to relieve this bug: Version 1.4.16 ...  [[http://lists.gnupg.org/pipermail/gnupg-announce/2013q4/000337.html][{more}]]

** Libgcrypt 1.6.0 released (2013-10-16)

The GNU project is pleased to announce the availability of Libgcrypt
version 1.6.0.  This is the new stable version of Libgcrypt with the API
being mostly compatible to previous versions.  Due to the removal of
certain long deprecated functions this version introduces an ABI
change.

The main features of this version are performance improvements,
better support for elliptic curves, new algorithms and modes, as well as
API and internal cleanups.  [[http://lists.gnupg.org/pipermail/gnupg-announce/2013q4/000336.html][{more}]]

** Blog: Preparing for launch (2013-12-13)

Mid December, giving season, and nearly time for the GnuPG Crowdfunding
to commence. We've been working hard on preparations ...
[[http://blog.gnupg.org/][{more}]]

** Blog: Friends tell friends they love GnuPG (2013-11-13)

Using GnuPG for email encryption takes two to tango. That's why
we're asking users to share their stories using #iloveGPG ...
[[http://blog.gnupg.org/][{more}]]

** New website infrastructure (2013-11-12)

After more than a decade we switched from the legacy WML based website
system to a new [[http://org-mode.org][org-mode]] based one.  The old WML code was not anymore
maintainable and building the website took way to long.  The new
system uses plain text files and will make it way easier to keep
information up to date.  Unfortunately the translations are gone for
now --- most of them have not been updated for many years anyway.

** Blog: Securing the future of GPG (2013-11-05)

We have a plan for securing the long term stability of GnuPG
development by giving more to our users, and asking more from them in
return ...  [[http://blog.gnupg.org/][{more}]]

** Security update for GnuPG (2013-10-05)                         :important:

We are pleased to announce the availability of a new stable GnuPG
release: Version 2.0.22 ...
[[http://lists.gnupg.org/pipermail/gnupg-announce/2013q4/000333.html][{more}]]

** Security update for GnuPG (2013-10-05)                         :important:

We are pleased to announce the availability of a new stable GnuPG
release: Version 1.4.15 ...
[[http://lists.gnupg.org/pipermail/gnupg-announce/2013q4/000334.html][{more}]]


** GnuPG 2.0.21 released (2013-08-19)

We are pleased to announce the availability of GnuPG 2.0.21. ...
[[http://lists.gnupg.org/pipermail/gnupg-announce/2013q3/000332.html][{more}]]


** Security update for GnuPG (2013-07-25)                         :important:

We are pleased to announce the availability of a new stable GnuPG
release: Version 1.4.14 ...
[[http://lists.gnupg.org/pipermail/gnupg-announce/2013q3/000329.html][{more}]]


** Security update for Libgcrypt (2013-07-25)                     :important:

We are pleased to announce the availability of a new stable Libgcrypt
release: Version 1.5.3 ...
[[http://lists.gnupg.org/pipermail/gnupg-announce/2013q3/000329.html][{more}]]


** GnuPG 2.0.20 released (2013-05-10 18:59:01)

We are pleased to announce the availability of GnuPG 2.0.20. ...
[[http://lists.gnupg.org/pipermail/gnupg-announce/2013q2/000328.html][{more}]]


** GnuPG 1.4.13 released  (2012-12-20 21:51:56)

We are pleased to announce the availability of a new stable GnuPG
release: Version 1.4.13 ...
[[http://lists.gnupg.org/pipermail/gnupg-announce/2012q4/000319.html][{more}]]


** GnuPG 2.0.19 released (2012-03-27 11:22:13)

We are pleased to announce the availability of GnuPG 2.0.19. ...
[[http://lists.gnupg.org/pipermail/gnupg-announce/2012q1/000314.html][{more}]]

** GnuPG 1.4.12 released (2012-01-30 17:39:22)

We are pleased to announce the availability of a new stable GnuPG
release: Version 1.4.12 ...
[[http://lists.gnupg.org/pipermail/gnupg-announce/2012q1/000313.html][{more}]]



* COMMENT
This is the publishing info used for the GnuPG pages
#+begin_src emacs-lisp
  (progn
   (setq gpgweb-root-dir (file-name-directory (buffer-file-name)))
   (require 'gpgweb (concat gpgweb-root-dir "share/gpgweb.el"))
   (setq org-export-html-toplevel-hlevel 1)
   (setq org-export-html-coding-system 'utf-8)
   (gpgweb-setup-project))
#+end_src
