#+TITLE: The GNU Privacy Guard
#+STARTUP: showall
#+SETUPFILE: "share/setup.inc"

* The GNU Privacy Guard
#+index: GnuPG
#+index: GPG
#+index: PGP
#+index: Gpg4win

GnuPG is a complete and free implementation of the OpenPGP standard as
defined by [[http://www.ietf.org/rfc/rfc4880.txt][RFC4880]] (also known as /PGP/). GnuPG allows to encrypt and
sign your data and communication, features a versatile key management
system as well as access modules for all kinds of public key
directories. GnuPG, also known as /GPG/, is a command line tool with
features for easy integration with other applications. A wealth of
[[file:related_software/frontends.html][frontend applications]] and [[file:related_software/libraries.html][libraries]] are available. Version 2 of GnuPG
also provides support for S/MIME and Secure Shell (ssh).

GnuPG is [[http://www.gnu.org/philosophy/free-sw.html][Free Software]] (meaning that it respects your freedom). It can
be freely used, modified and distributed under the terms of the
[[http://www.gnu.org/copyleft/gpl.html][GNU General Public License]] .

GnuPG comes in three flavours:

 - {{{gnupg_ver}}} is the /stable/ version suggested for most users,

 - {{{gnupg21_ver}}} is the brand-new /modern/ version with support
   for [[https://en.wikipedia.org/wiki/Elliptic_curve_cryptography][ECC]] and many other new features,

 - and {{{gnupg1_ver}}} is the /classic/ portable version.

Project [[http://www.gpg4win.org][Gpg4win]] provides a Windows version of GnuPG /stable/. It is
nicely integrated into an installer and features several frontends as
well as English and German manuals.

* Reconquer your privacy

Even if you have nothing to hide, using encryption helps protect the
privacy of people you communicate with, and makes life difficult for
bulk surveillance systems. If you do have something important to hide,
you are in good company; GnuPG is one of the tools that Edward Snowden
used to uncover his secrets about the NSA.

Please visit the [[https://emailselfdefense.fsf.org][Email Self-Defense]] site to learn how and why you
should use GnuPG for your electronic communication.  If you need
printed leaflets check out [[https://fsfe.org/contribute/spreadtheword.html#gnupg-leaflet][FSFE’s GnuPG leaflet]].


* News
#+index: News

The latest blog entries:
#+begin_html
<ul>
<!--INSERT-BLOG-HEADLINE-->
</ul>
#+end_html

The latest release news:\\
([[file:news.org][all news]])

# For those of you who like reading world’s news with an RSS reader,
# GnuPG's latest news are available as [[http://feedvalidator.org/check.cgi?url%3Dhttps://www.gnupg.org/news.en.rss][RSS 2.0 compliant]] feed.  Just
# point or paste the [[news.en.rss][RSS file]] into your aggregator.


** GnuPG 2.1.4 released (2015-04-11)

This is another release of the /modern/ branch of GnuPG.  It fixes
a lot of bugs.  Read the full [[https://lists.gnupg.org/pipermail/gnupg-announce/2015q2/000365.html][anouncement mail]].

** GnuPG 1.4.19 released (2015-02-27)                             :important:

GnuPG 1.4.19 is now available.  This release mitigates two new of side
channel attack methods as well as a couple of other bugs.  [[http://lists.gnupg.org/pipermail/gnupg-announce/2015q1/000363.html][{more}]]

** Libgcrypt 1.6.3 released (2015-02-27)                          :important:

Libgcrypt version 1.6.3 has been released to mitigate two new side
channel attack methods.  [[http://lists.gnupg.org/pipermail/gnupg-announce/2015q1/000364.html][{more}]]

** GnuPG 2.0.27 released (2015-02-18)

GnuPG 2.0.27 is now available.  This release fixes a couple of bugs;
users of GnuPG 2.0.x should update to this version.  [[http://lists.gnupg.org/pipermail/gnupg-announce/2015q1/000362.html][{more}]]

** GnuPG 2.1.2 released (2015-02-11)

This is the third release of the /modern/ branch of GnuPG.  It fixes
a lot of bugs.  Read the full [[https://lists.gnupg.org/pipermail/gnupg-announce/2015q1/000361.html][anouncement mail]].

** GnuPG 2.1.1 released (2014-12-16)

This is the second release of the /modern/ branch of GnuPG.  It fixes
a lot of bugs and brings some new features.  Read more about 2.1 at
the [[file:faq/whats-new-in-2.1.org][feature overview]] page and in the [[http://lists.gnupg.org/pipermail/gnupg-announce/2014q4/000360.html][announcement]] mail.


** Libksba 1.3.2 released (2014-11-25)                            :important:

This is a security fix release and all users of Libksba should update
to this version.  Note that *GnuPG 2.x* makes use of Libksba and thus
all user of GnuPG 2.x need to install this new version of Libksba and
restart the dirmngr process.  Read the full [[http://lists.gnupg.org/pipermail/gnupg-announce/2014q4/000359.html][announcement]].


** GnuPG 2.1.0 with ECC support released (2014-11-06)

This is the first release of the new /modern/ branch of GnuPG.  It
features a lot of new things including support for ECC.  Read more at
the [[file:faq/whats-new-in-2.1.org][feature overview]] page and in the [[http://lists.gnupg.org/pipermail/gnupg-announce/2014q4/000358.html][announcement]] mail.


* A big Thanks to all supporters

Due to this [[http://www.propublica.org/article/the-worlds-email-encryption-software-relies-on-one-guy-who-is-going-broke][ProPublica article]] we received more than 120,000 \euro of
individual donations on a single day.  There was even more: The [[http://www.linuxfoundation.org/programs/core-infrastructure-initiative][Core
Infrastructure Initiative]] granted 60,000 $ for 2015.  Our payment
service [[https://twitter.com/stripe/status/563449352635432960][Stripe]] and [[https://www.facebook.com/notes/protect-the-graph/supporting-gnu-privacy-guard/1564591893780956][Facebook]] will each give 50,000 $ to the project.
And finally the [[https://www.wauland.de/en/donation.html#61][Wau Holland Stiftung]] is collecting tax deductible
funds for GnuPG (19000 \euro plus 57 BTC).

As the main author of GnuPG, I like to thank everyone for supporting
the project, be it small or large individual donations, helping users,
providing corporate sponsorship, working on the software, and for all
the encouraging words.

GnuPG does not stand alone: there are many other projects, often
unknown to most people, which are essential to keep the free Internet
running.  Many of them are run by volunteers who spend a lot of unpaid
time on them.  They need our support as well.

/--- Werner, 2015-02-06/

(see also this [[https://gnupg.org/blog/20150310-gnupg-in-february.html][blog]] entry)

* COMMENT
This is the publishing info used for the GnuPG pages
#+begin_src emacs-lisp
  (progn
   (setq gpgweb-root-dir (file-name-directory (buffer-file-name)))
   (require 'gpgweb (concat gpgweb-root-dir "share/gpgweb.el"))
   (setq org-publish-use-timestamps-flag nil)
   (setq org-export-html-toplevel-hlevel 1)
   (setq org-export-html-coding-system 'utf-8)
   (gpgweb-setup-project))
#+end_src
