#+TITLE: The GNU Privacy Guard
#+STARTUP: showall
#+SETUPFILE: "share/setup.inc"
#+GPGWEB-NEED-SWDB

* The GNU Privacy Guard
#+index: GnuPG
#+index: GPG
#+index: PGP
#+index: Gpg4win

GnuPG is a complete and free implementation of the OpenPGP standard as
defined by [[https://www.ietf.org/rfc/rfc4880.txt][RFC4880]] (also known as /PGP/). GnuPG allows you to encrypt and
sign your data and communications; it features a versatile key management
system, along with access modules for all kinds of public key
directories.  GnuPG, also known as /GPG/, is a command line tool with
features for easy integration with other applications.  A wealth of
[[file:software/frontends.html][frontend applications]] and [[file:software/libraries.html][libraries]] are available.  GnuPG also
provides support for S/MIME and Secure Shell (ssh).

Since its introduction in 1997, GnuPG is [[https://www.gnu.org/philosophy/free-sw.html][Free Software]] (meaning that
it respects your freedom). It can be freely used, modified and
distributed under the terms of the [[https://www.gnu.org/copyleft/gpl.html][GNU General Public License]] .

The current version of GnuPG is {{{gnupg22_ver}}}.  See the [[file:download/index.org][download]]
page for other maintained versions.

[[https://www.gpg4win.org][Gpg4win]] is a Windows version of GnuPG featuring a context menu tool, a
crypto manager, and an Outlook plugin to send and receive standard
PGP/MIME mails.  The current version of Gpg4win is {{{gpg4win_ver}}}.

* Reconquer your privacy

#+begin_quote
Arguing that you don't care about the right to privacy
because you have nothing to hide is no different from
saying you don't care about free speech because you have
nothing to say.   \ndash\nbsp{}Edward\nbsp{}Snowden
#+end_quote

Using encryption helps to protect your privacy and the privacy of the
people you communicate with.  Encryption makes life difficult for bulk
surveillance systems.  GnuPG is one of the tools that Snowden used to
uncover the secrets of the NSA.

Please visit the [[https://emailselfdefense.fsf.org][Email Self-Defense]] site to learn how and why you
should use GnuPG for your electronic communication.


* News
#+index: News

The latest blog entries:
#+begin_html
<ul>
<!--INSERT-BLOG-HEADLINE-->
</ul>
#+end_html

The latest release news:\\
([[file:news.org][all news]])

# For those of you who like reading world’s news with an RSS reader,
# GnuPG's latest news are available as [[http://feedvalidator.org/check.cgi?url%3Dhttps://www.gnupg.org/news.en.rss][RSS 2.0 compliant]] feed.  Just
# point or paste the [[news.en.rss][RSS file]] into your aggregator.

** GnuPG 2.2.24 released (2020-11-17)

GnuPG version 2.2.24 has been released today.  This is a maintenance
release fixing some longstanding bugs.  {[[https://lists.gnupg.org/pipermail/gnupg-announce/2020q4/000449.html][more]]}

** GnuPG 2.2.23 released (2020-09-03)                             :important:

GnuPG version 2.2.23 has been released today.  This version fixes a
*critical security bug* in 2.2.21 and 2.2.22 ({{{CVE(2020-25125)}}}).

Please follow the instructions from the [[https://lists.gnupg.org/pipermail/gnupg-announce/2020q3/000448.html][announcement mail]] and update
affected installations.  See also our bug entry [[https://dev.gnupg.org/T5050][#5050]].

** GnuPG 2.2.22 released (2020-08-27)

[Note: Do not use this release - use 2.2.23 instead.]

GnuPG version 2.2.22 has been released today.  This is a maintenance
release with a some minor changes.  {[[https://lists.gnupg.org/pipermail/gnupg-announce/2020q3/000447.html][more]]}


** GnuPG 2.2.21 released (2020-07-09)

[Note: Do not use this release - use 2.2.23 instead.]

After the release of GnuPG [[https://lists.gnupg.org/pipermail/gnupg-announce/2020q1/000444.html][2.2.20]] back in March it is now the time to
get collected fixes from the last months out: GnuPG version 2.2.21 has
been released today.  This is a maintenance release with a some minor
changes.  {[[https://lists.gnupg.org/pipermail/gnupg-announce/2020q3/000446.html][more]]}

** Libgcrypt 1.8.6 released (2020-07-06)

Nearly a year passed since the last release and so the time is ripe
for new maintenance release: [[file:software/libgcrypt/index.org][Libgcrypt]] version 1.8.6 is now
available. {[[https://lists.gnupg.org/pipermail/gnupg-announce/2020q3/000445.html][more]]}

** Gpg4win fully approved for EU RESTRICTED.

After about a year of tweaking details of the approval, Gpg4win and
GnuPG are now approved for EU RESTRICTED communication (VS-NfD).  This
approvals covers the protocols S/MIME and OpenPGP (public-key and
symmetric-only) with hard- and soft-tokens.  Our commercial branch
[[https://gnupg.com][GnuPG.com]] released a [[https://gnupg.com/20200107-freigabe-vs-nfd.html][press notice]] (in German) today.


** GnuPG 2.2.19 released (2019-12-07)

We are pleased to announce the availability of GnuPG version 2.2.19.
This version fixes a regression introduced with the last release.
{[[https://lists.gnupg.org/pipermail/gnupg-announce/2019q4/000443.html][more]]}

** GnuPG 2.2.18 released (2019-11-25)

We are pleased to announce the availability of GnuPG version 2.2.18.
This is maintenance release to fix a couple of minor bugs and provide
a few feature updates.  This release also retires the use of SHA-1 key
signatures created since this year. {[[https://lists.gnupg.org/pipermail/gnupg-announce/2019q4/000442.html][more]]} ([[https://lists.gnupg.org/pipermail/gnupg-announce/2019q4/000443.html][see also]])

** Libgcrypt 1.8.5 released (2019-08-29)

If you care about local site-channel attacks on ECDSA you may want to
update to [[file:software/libgcrypt/index.org][Libgcrypt]] version 1.8.5. {{{CVE(CVE-2019-13627)}}} {[[https://lists.gnupg.org/pipermail/gnupg-announce/2019q3/000440.html][more]]}

* COMMENT
This is the publishing info used for the GnuPG pages
#+begin_src emacs-lisp
  (progn
   (setq gpgweb-root-dir (file-name-directory (buffer-file-name)))
   (setq gpgweb-stage-dir (concat gpgweb-root-dir "../stage"))
   (require 'gpgweb (concat gpgweb-root-dir "share/gpgweb.el"))
   (setq org-publish-use-timestamps-flag nil)
   (setq org-export-html-toplevel-hlevel 1)
   (setq org-export-html-coding-system 'utf-8)
   (gpgweb-setup-project))
#+end_src
