#+TITLE: GnuPG - All News
#+STARTUP: showall

* All News

On this page you'll find all the news of previous years in reverse
chronological order.  News for the current year are found at the [[index][main
page]].

** GnuPG 2.1.14 released (2016-07-14)

A new version of the /modern/ branch of GnuPG has been released.
Read the full [[https://lists.gnupg.org/pipermail/gnupg-announce/2016q3/000393.html][announcement mail]] for details.

** Libgcrypt 1.7.2 released (2016-07-14)

We are pleased to announce the availability of Libgcrypt version
1.7.2.  This is a maintenance release for the stable version of
[[file:software/libgcrypt/index.org][Libgcrypt]] with a few bug fixes. [[https://lists.gnupg.org/pipermail/gnupg-announce/2016q3/000392.html][{more}]]

** GnuPG 2.1.13 released (2016-06-16)

A new version of the /modern/ branch of GnuPG has been released.
Read the full [[https://lists.gnupg.org/pipermail/gnupg-announce/2016q2/000390.html][announcement mail]] for details.

** Libgcrypt 1.7.1 released (2016-06-15)

We are pleased to announce the availability of Libgcrypt version
1.7.1.  This is a maintenance release for the stable version of
[[file:software/libgcrypt/index.org][Libgcrypt]] with a few bug fixes. [[https://lists.gnupg.org/pipermail/gnupg-announce/2016q2/000389.html][{more}]]

** First OpenPGP conference (2016-05-20)

If you are a user or implementer of OpenPGP related software, you may
join us at [[https://gnupg.org/conf/][OpenPGP.conf]] in Cologne on September 8 and 9, 2016.

** GnuPG 2.1.12 released (2016-05-04)

A new version of the /modern/ branch of GnuPG has been released.
Read the full [[https://lists.gnupg.org/pipermail/gnupg-announce/2016q2/000387.html][announcement mail]] for details.

** Libgcrypt 1.7.0 released (2016-04-15)

We are pleased to announce the availability of Libgcrypt version
1.7.0.  This is a new stable version of [[file:software/libgcrypt/index.org][Libgcrypt]] with full API and
ABI compatibiliy to the 1.6 series.  Its main features are new
algorithms, curves, and performance improvements.  [[https://lists.gnupg.org/pipermail/gnupg-announce/2016q2/000386.html][{more}]]

** GnuPG 2.0.30 released (2016-03-31)

GnuPG 2.0.30 is now available.  This release fixes a few minor bugs;
users of GnuPG 2.0.x may want to update to this version.  [[https://lists.gnupg.org/pipermail/gnupg-announce/2016q1/000385.html][{more}]]

** Libgcrypt 1.6.5 released (2016-02-09) 			  :important:

Libgcrypt version 1.6.5 and an updated Windows installer for GnuPG
2.1.11 has been released to mitigate a new side-channel attack.
[[https://lists.gnupg.org/pipermail/gnupg-announce/2016q1/000384.html][{more}]]

** GnuPG 2.1.11 released (2016-01-26)

A new version of the /modern/ branch of GnuPG has been released.
Read the full [[https://lists.gnupg.org/pipermail/gnupg-announce/2016q1/000383.html][announcement mail]] for details.


** GnuPG 1.4.20 released (2015-12-20)

18 years after the first GnuPG release version 1.4.20 has been
released today.  This release from the /classic/ branch of GnuPG now
also rejects the insecure MD5 signatures created by PGP-2 (unless the
=--pgp2= option is used).  [[https://lists.gnupg.org/pipermail/gnupg-announce/2015q4/000382.html][{more}]]

** GnuPG 2.1.10 released (2015-12-04)

A new version of the /modern/ branch of GnuPG has been released.  The
main features of this release are support for [[https://en.wikipedia.org/wiki/Trust_on_first_use][TOFU]] and anonymous key
retrieval via [[https://www.torproject.org][Tor]].  Read the full [[https://lists.gnupg.org/pipermail/gnupg-announce/2015q4/000381.html][announcement mail]] for details.

** GnuPG 2.1.9 released (2015-10-09)

A new version of the /modern/ branch of GnuPG has been released.
Read the full [[https://lists.gnupg.org/pipermail/gnupg-announce/2015q4/000380.html][announcement mail]] for details.

** GnuPG 2.1.8 released (2015-09-10)

A new version of the /modern/ branch of GnuPG has been released.
Read the full [[https://lists.gnupg.org/pipermail/gnupg-announce/2015q3/000379.html][announcement mail]] for details.

** GPA 0.9.9 released (2015-09-09)

A new version of [[file:software/gpa/index.org][GPA]], the graphical frontend for GnuPG, is now
available.  This release fixes a couple of bugs and has been changed
to show the clipboard view on startup.  [[https://lists.gnupg.org/pipermail/gnupg-announce/2015q3/000378.html][{more}]]

** GnuPG 2.0.29 released (2015-09-08)

GnuPG 2.0.29 is now available.  This release fixes a couple of bugs;
users of GnuPG 2.0.x may want to update to this version.  [[https://lists.gnupg.org/pipermail/gnupg-announce/2015q3/000376.html][{more}]]

** Libgcrypt 1.6.4 released (2015-09-08)

Libgcrypt version 1.6.4 has been released to fix a few minor bugs and
a crash on newer Windows versions. [[https://lists.gnupg.org/pipermail/gnupg-announce/2015q3/000375.html][{more}]]

** Libassuan 2.3.0 released (2015-08-28)

[[file:software/libassuan/index.org][Libassuan]] is a generic [[https://en.wikipedia.org/wiki/Inter-process_communication][IPC]] library used by GnuPG, GPGME, and a few
other packages.  This release fixes two bugs and introduces new
support functions for the socket wrappers.  See [[https://lists.gnupg.org/pipermail/gnupg-announce/2015q3/000374.html][here]] for details.

** GPGME 1.6.0 and Libgpg-error 1.20 released (2015-08-26)

GPGME 1.6.0 is now available.  This release introduce a mode to export
sceret keys, improves the error return codes, and is prepared to make
use of the GnuPG 2.1 Windows installer.  See this full [[https://lists.gnupg.org/pipermail/gnupg-announce/2015q3/000372.html][announcement]].
An update of Libgpg-error to fix a problem in Windows has also been
released; see this [[https://lists.gnupg.org/pipermail/gnupg-announce/2015q3/000373.html][announcement]].

** GnuPG 2.1.7 released (2015-08-11)

A new version of the /modern/ branch of GnuPG has been released.
Read the full [[https://lists.gnupg.org/pipermail/gnupg-announce/2015q3/000371.html][announcement mail]] for details.

** GnuPG 2.1.6 released (2015-07-01)

A new version of the /modern/ branch of GnuPG has been released.
Read the full [[https://lists.gnupg.org/pipermail/gnupg-announce/2015q3/000370.html][announcement mail]] for details.

** GnuPG 2.1.5 released (2015-06-11)

A new version of the /modern/ branch of GnuPG has been released.
Read the full [[https://lists.gnupg.org/pipermail/gnupg-announce/2015q2/000369.html][announcement mail]] for details.

** GPGME 1.5.5 released (2015-06-08)

GPGME 1.5.5 is now available.  This release fixes a crash due to
malformed user ids and a regression when gpgsm < 2.1 is used.  See the
full [[https://lists.gnupg.org/pipermail/gnupg-announce/2015q2/000368.html][{announcement}]] mail.

** GnuPG 2.0.28 released (2015-06-02)

GnuPG 2.0.28 is now available.  This release fixes a couple of bugs;
users of GnuPG 2.0.x should update to this version.  [[https://lists.gnupg.org/pipermail/gnupg-announce/2015q2/000367.html][{more}]]

** GnuPG 2.1.4 released (2015-05-12)

A new version of the /modern/ branch of GnuPG has been released.
Read the full [[https://lists.gnupg.org/pipermail/gnupg-announce/2015q2/000366.html][announcement mail]] for details.

** GnuPG 2.1.3 released (2015-04-11)

This is another release of the /modern/ branch of GnuPG.  It fixes
a lot of bugs.  Read the full [[https://lists.gnupg.org/pipermail/gnupg-announce/2015q2/000365.html][announcement mail]].

** GnuPG 1.4.19 released (2015-02-27)                             :important:

GnuPG 1.4.19 is now available.  This release mitigates two new of side
channel attack methods as well as a couple of other bugs.  [[https://lists.gnupg.org/pipermail/gnupg-announce/2015q1/000363.html][{more}]]

** Libgcrypt 1.6.3 released (2015-02-27)                          :important:

Libgcrypt version 1.6.3 has been released to mitigate two new side
channel attack methods.  [[https://lists.gnupg.org/pipermail/gnupg-announce/2015q1/000364.html][{more}]]

** GnuPG 2.0.27 released (2015-02-18)

GnuPG 2.0.27 is now available.  This release fixes a couple of bugs;
users of GnuPG 2.0.x should update to this version.  [[https://lists.gnupg.org/pipermail/gnupg-announce/2015q1/000362.html][{more}]]

** GnuPG 2.1.2 released (2015-02-11)

This is the third release of the /modern/ branch of GnuPG.  It fixes
a lot of bugs.  Read the full [[https://lists.gnupg.org/pipermail/gnupg-announce/2015q1/000361.html][announcement mail]].

** GnuPG 2.1.1 released (2014-12-16)

This is the second release of the /modern/ branch of GnuPG.  It fixes
a lot of bugs and brings some new features.  Read more about 2.1 at
the [[file:faq/whats-new-in-2.1.org][feature overview]] page and in the [[https://lists.gnupg.org/pipermail/gnupg-announce/2014q4/000360.html][announcement]] mail.


** Libksba 1.3.2 released (2014-11-25)                            :important:

This is a security fix release and all users of Libksba should update
to this version.  Note that *GnuPG 2.x* makes use of Libksba and thus
all user of GnuPG 2.x need to install this new version of Libksba and
restart the dirmngr process.  Read the full [[https://lists.gnupg.org/pipermail/gnupg-announce/2014q4/000359.html][announcement]].


** GnuPG 2.1.0 with ECC support released (2014-11-06)

This is the first release of the new /modern/ branch of GnuPG.  It
features a lot of new things including support for ECC.  Read more at
the [[file:faq/whats-new-in-2.1.org][feature overview]] page and in the [[https://lists.gnupg.org/pipermail/gnupg-announce/2014q4/000358.html][announcement]] mail.

** A beta for GnuPG 2.1.0 released (2014-10-03)

A beta release for the forthcoming GnuPG 2.1 version is now
available.  [[https://lists.gnupg.org/pipermail/gnupg-announce/2014q4/000357.html][{more}]]

** GPA 0.95 released

GPA is the GNU Privacy Assistant, a frontend to GnuPG.  This new
release has support for ECC keys and improves on the UI server
feature.  [[https://lists.gnupg.org/pipermail/gnupg-announce/2014q3/000356.html][{more}]]

** GnuPG 2.0.26 released (2014-08-12)

GnuPG 2.0.26 is now available.  This is a maintenance release.  [[https://lists.gnupg.org/pipermail/gnupg-announce/2014q3/000353.html][{more}]]

** Libgcrypt 1.5.4 security fix release                           :important:

Using any Libgcrypt version less than 1.5.4 with GnuPG 2.0.x and
Elgamal encryption keys is vulnerable to the /Get Your Hands Off My
Laptop/ attack.  Please update to the newly released Libgcrypt 1.5.4
or a 1.6 version.  [[https://lists.gnupg.org/pipermail/gnupg-announce/2014q3/000352.html][{more}]]

** Get Your Hands Off My Laptop (2014-08-07)

Daniel Genkin, Itamar Pipman, and Eran Tromer latest side channel
attack targets an /older version/ of GnuPG.  If your GnuPG and
Libgcrypt versions are up-to-date you are safe.  [[https://lists.gnupg.org/pipermail/gnupg-announce/2014q3/000349.html][{more}]]

** GPGME 1.5.1 and 1.4.4 released (2014-08-07)                    :important:

A security fix release for the GPGME library is available.  It is
suggested to update to one of these version.  [[https://lists.gnupg.org/pipermail/gnupg-announce/2014q3/000350.html][{more}]]

** GnuPG 2.0.25 and 1.4.18 released (2014-06-30)

To fix a minor regression in the previous releases we released today
new versions of GnuPG-1 and GnuPG-2: [[https://lists.gnupg.org/pipermail/gnupg-announce/2014q2/000346.html][{2.0.25}]], [[https://lists.gnupg.org/pipermail/gnupg-announce/2014q2/000347.html][{1.4.18}]]

** GnuPG 2.0.24 released (2014-06-24)                             :important:

GnuPG 2.0.24 is now available.  This GnuPG-2 release features a fix
for a denial of service attack and a few other changes.  [[https://lists.gnupg.org/pipermail/gnupg-announce/2014q2/000345.html][{more}]]


** GnuPG 1.4.17 released (2014-06-23)                             :important:

GnuPG 1.4.17 is now available.  This GnuPG-1 release features a fix
for a denial of service attack and a few other minor changes.  [[https://lists.gnupg.org/pipermail/gnupg-announce/2014q2/000344.html][{more}]]


** GnuPG 2.0.23 released (2014-06-03)

We are pleased to announce the availability of GnuPG 2.0.23.  This is
a maintenance release with a few new features. [[https://lists.gnupg.org/pipermail/gnupg-announce/2014q2/000342.html][{more}]]


** Goteo campaign: preliminary results (2014-05-12)

The blog has a report on the current status of the campaign including
an overview of the financial results.  [[https://www.gnupg.org/blog/20140512-rewards-sent.html][{read here}]]

** Mission complete: campaign ends, closing stats (2014-02-06)

After 50 days of crowdfunding, the GnuPG campaign for new website and
infrastructure will close tomorrow. That means rewards for backers can
now be ordered and preparations for dispatch can begin. Here are the
results so far.  [[https://www.gnupg.org/blog/20140206-crowdfunding-complete.html][{more}]]


** 16 Years of protecting privacy (2013-12-20)

Today marks 16 years since the first release of GnuPG. In that time
the project has grown from being a hacker’s hobby into one of the
world’s most critical anti-surveillance tools.  Today GnuPG stands at
the front line of the battle between invasive surveillance and civil
liberties.  [[https://www.gnupg.org/blog/20131220-gnupg-turned-0x10.html][{more}]]

** GnuPG launches crowdfunding campaign (2013-12-19)

Today GNU Privacy Guard (GnuPG) has launched its first
[[http://goteo.org/project/gnupg-new-website-and-infrastructure][crowdfunding campaign]] with the aim of building a new website and long term
infrastructure.  [[https://lists.gnupg.org/pipermail/gnupg-announce/2013q4/000338.html][{more}]] [[https://www.gnupg.org/blog/20131219-gnupg-launches-crowfunding.de.html][{deutsch}]] [[https://www.gnupg.org/blog/20131219-gnupg-launches-crowfunding.fr.html][{francaise}]]

** GnuPG 1.4.16 released (2013-12-18)                             :important:

Along with the publication of an interesting new [[http://www.cs.tau.ac.il/~tromer/acoustic/][side channel attack]]
by Genkin, Shamir, and Tromer we announce the availability of a new
stable GnuPG release to relieve this bug: Version 1.4.16 ...  [[https://lists.gnupg.org/pipermail/gnupg-announce/2013q4/000337.html][{more}]]

** Blog: Getting Goteo crowdfunding approval (2013-12-18)

The targets are set, the rewards are prepared, the press release has
been edited and translated, and now we're waiting for approval from
the crowdfunding platform Goteo ...   [[https://www.gnupg.org/blog/20131218-getting-goteo-approval.html][{more}]]

** GnuPG 1.4.16 released (2013-12-18)                             :important:

Along with the publication of an interesting new [[http://www.cs.tau.ac.il/~tromer/acoustic/][side channel attack]]
by Genkin, Shamir, and Tromer we announce the availability of a new
stable GnuPG release to relieve this bug: Version 1.4.16 ...  [[https://lists.gnupg.org/pipermail/gnupg-announce/2013q4/000337.html][{more}]]

** Libgcrypt 1.6.0 released (2013-10-16)

The GNU project is pleased to announce the availability of Libgcrypt
version 1.6.0.  This is the new stable version of Libgcrypt with the API
being mostly compatible to previous versions.  Due to the removal of
certain long deprecated functions this version introduces an ABI
change.

The main features of this version are performance improvements,
better support for elliptic curves, new algorithms and modes, as well as
API and internal cleanups.  [[https://lists.gnupg.org/pipermail/gnupg-announce/2013q4/000336.html][{more}]]

** Blog: Preparing for launch (2013-12-13)

Mid December, giving season, and nearly time for the GnuPG Crowdfunding
to commence. We've been working hard on preparations ...
[[https://www.gnupg.org/blog/index.html][{more}]]

** Blog: Friends tell friends they love GnuPG (2013-11-13)

Using GnuPG for email encryption takes two to tango. That's why
we're asking users to share their stories using #iloveGPG ...
[[https://www.gnupg.org/blog/index.html][{more}]]

** New website infrastructure (2013-11-12)

After more than a decade we switched from the legacy WML based website
system to a new [[http://org-mode.org][org-mode]] based one.  The old WML code was not anymore
maintainable and building the website took way to long.  The new
system uses plain text files and will make it way easier to keep
information up to date.  Unfortunately the translations are gone for
now --- most of them have not been updated for many years anyway.

** Blog: Securing the future of GPG (2013-11-05)

We have a plan for securing the long term stability of GnuPG
development by giving more to our users, and asking more from them in
return ...  [[https://www.gnupg.org/blog/index.html][{more}]]

** Security update for GnuPG (2013-10-05)                         :important:

We are pleased to announce the availability of a new stable GnuPG
release: Version 2.0.22 ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2013q4/000333.html][{more}]]

** Security update for GnuPG (2013-10-05)                         :important:

We are pleased to announce the availability of a new stable GnuPG
release: Version 1.4.15 ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2013q4/000334.html][{more}]]


** GnuPG 2.0.21 released (2013-08-19)

We are pleased to announce the availability of GnuPG 2.0.21. ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2013q3/000332.html][{more}]]


** Security update for GnuPG (2013-07-25)                         :important:

We are pleased to announce the availability of a new stable GnuPG
release: Version 1.4.14 ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2013q3/000329.html][{more}]]


** Security update for Libgcrypt (2013-07-25)                     :important:

We are pleased to announce the availability of a new stable Libgcrypt
release: Version 1.5.3 ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2013q3/000329.html][{more}]]


** GnuPG 2.0.20 released (2013-05-10 18:59:01)

We are pleased to announce the availability of GnuPG 2.0.20. ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2013q2/000328.html][{more}]]


** GnuPG 1.4.13 released  (2012-12-20 21:51:56)

We are pleased to announce the availability of a new stable GnuPG
release: Version 1.4.13 ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2012q4/000319.html][{more}]]


** GnuPG 2.0.19 released (2012-03-27 11:22:13)

We are pleased to announce the availability of GnuPG 2.0.19. ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2012q1/000314.html][{more}]]

** GnuPG 1.4.12 released (2012-01-30 17:39:22)

We are pleased to announce the availability of a new stable GnuPG
release: Version 1.4.12 ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2012q1/000313.html][{more}]]


** GnuPG 1.4.13 released  (2012-12-20 21:51:56)

Wir freuen uns, Ihnen die Verfügbarkeit von GnuPG 1.4.13 bekannt
zu geben.
[[https://lists.gnupg.org/pipermail/gnupg-announce/2012q4/000319.html][{more}]]


** GnuPG 2.0.19 released  (2012-03-27 11:22:13)

We are pleased to announce the availability of GnuPG 2.0.19. ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2012q1/000314.html][{more}]]

** GnuPG 1.4.12 released  (2012-01-30 17:39:22)

We are pleased to announce the availability of a new stable GnuPG
release: Version 1.4.12.  ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2012q1/000313.html][{more}]]


** STEED project announced (2011-10-17 20:15:22)

STEED - Usable end-to-end encryption ...
[[https://lists.gnupg.org/pipermail/gnupg-devel/2011-October/026264.html][{more}]]

** GnuPG 2.0.18 released (2011-08-04 18:19:36)

We are pleased to announce the availability of GnuPG 2.0.18. ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2011q3/000312.html][{more}]]

** Libgcrypt 1.5.0 released (2011-06-29 12:21:39)

We are pleased to announce the availability of Libgcrypt 1.5.0. This is
the new stable version of Libgcrypt and upward compatible with the 1.4
series. ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2011q2/000307.html][{more}]]

** GnuPG 2.0.17 released (2011-01-13 17:20:12)

We are pleased to announce the availability of GnuPG 2.0.17. ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2011q1/000305.html][{more}]]

** GnuPG 1.4.11 released (2010-10-18 13:36:14)

We are pleased to announce the availability of a new stable GnuPG
release: Version 1.4.11 ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2010q4/000303.html][{more}]]

** Important security update for GnuPG (2010-07-23 14:38:50)

While trying to import a server certificate for a CDN service, a segv
bug was found in GnuPG's GPGSM tool. It is likely that this bug is
exploitable by sending a special crafted signed message and having a
user verify the signature. A simple patch is available ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2010q3/000302.html][{more}]]

** GnuPG 2.0.16 released (2010-07-19 10:44:59)

We are pleased to announce the availability of GnuPG 2.0.16. ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2010q3/000301.html][{more}]]

** GnuPG 2.0.15 released (2010-03-09 11:44:13)

We are pleased to announce the availability of GnuPG 2.0.15. ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2010q1/000299.html][{more}]]


** GnuPG 2.0.14 released (2009-12-21 19:03:26)

We are pleased to announce the availability of GnuPG 2.0.14. ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2009q4/000296.html][{more}]]


** Libgcrypt 1.4.5 released (2009-12-11 17:51:12)

We are pleased to announce the availability of Libgcrypt 1.4.5. This is
the new stable version of Libgcrypt and upward compatible with the 1.2
series. ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2009q4/000295.html][{more}]]


** GnuPG 2.0.13 released (2009-09-04 19:12:01)

We are pleased to announce the availability of GnuPG 2.0.13. ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2009q3/000294.html][{more}]]

** GnuPG 1.4.10 released (2009-09-02 19:27:55)

We are pleased to announce the availability of a new stable GnuPG
release: Version 1.4.10 ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2009q3/000291.html][{more}]]


** GnuPG 2.0.12 released (2009-06-17 13:19:26)

We are pleased to announce the availability of GnuPG 2.0.12. ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2009q2/000288.html][{more}]]


** GnuPG 2.0.11 released (2009-03-03 13:02:51)

We are pleased to announce the availability of GnuPG 2.0.11 ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2009q1/000287.html][{more}]]


** Libgcrypt 1.4.4 released (2009-01-22 20:08:24)

We are pleased to announce the availability of Libgcrypt 1.4.4. This is
the new stable version of Libgcrypt and upward compatible with the 1.2
series. ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2009q1/000285.html][{more}]]


** GnuPG 2.0.10 released (2009-01-12 10:59:05)

We are pleased to announce the availability of GnuPG 2.0.10 ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2009q1/000284.html][{more}]]


** Signing key updated! (2009-01-09 12:58:02)

The expiration date of the key used to sign GnuPG distributions has been
prolonged for another year. Please update the key ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2009q1/000282.html][{more}]]


** GnuPG's 10th birthday! (2007-12-20 12:10:30)

It has been a decade since the very first version of the GNU Privacy
Guard was released ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2007q4/000268.html][{more}]]


** GnuPG 2.0.8 released (2007-12-20 12:09:30)

We are pleased to announce the availability of GnuPG 2.0.8 ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2007q4/000267.html][{more}]]


** GnuPG 1.4.8 released (2007-12-20 12:09:03)

We are pleased to announce the availability of a new stable GnuPG
release: Version 1.4.8. ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2007q4/000266.html][{more}]]

** Libgcrypt 1.4.0 released (2007-12-10 20:10:34)

We are pleased to announce the availability of Libgcrypt 1.4.0. This is
the new stable version of Libgcrypt and upward compatible with the 1.2
series. ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2007q4/000263.html][{more}]]


** New OpenPGP standard (2007-11-02 17:54:26)

The new OpenPGP standard has been published. It was assigned RFC number
4880. ...
[[https://lists.gnupg.org/pipermail/gnupg-users/2007-November/031994.html][{more}]]


** GnuPG 2.0.7 released (2007-09-10 19:18)

We are pleased to announce the availability of GnuPG 2.0.7 ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2007q3/000259.html][{more}]]


** GnuPG 2.0.6 released (2007-08-16 17:48)

We are pleased to announce the availability of GnuPG 2.0.6 ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2007q3/000258.html][{more}]]


** GnuPG 2.0.5 released (2007-07-06 12:46)

We are pleased to announce the availability of GnuPG 2.0.5 ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2007q3/000255.html][{more}]]


** Manual pages online (2007-05-11 11:45:30)

The manuals of GnuPG and some related software are now available online.
Check out the navigation bar or go directly to the
[[https://www.gnupg.org/documentation/manuals.html][overview page]] .


** GnuPG 2.0.4 released (2007-05-09 13:02)

We are pleased to announce the availability of GnuPG 2.0.4 ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2007q2/000254.html][{more}]]


** GnuPG 2.0.3 released (2007-03-08 16:55:25)

We are pleased to announce the availability of GnuPG 2.0.3 ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2007q1/000252.html][{more}]]


** Multiple Messages Problem in GnuPG and GPGME (2007-03-06 09:31:21)

A common usage problem of gpg has been identified. Instead of requiring
a fix for all these applications, GnuPG and GPGME have been changed to
provide the necessary protection. ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2007q1/000251.html][{more}]]


** Important security update for GnuPG(2006-12-06 17:18:35)

Tavis Ormandy of the Gentoo security team identified a severe and
exploitable bug in the processing of encrypted packets in GnuPG.
Updating is highly suggested. A new version of GnuPG (1.4.6) as well has
a patch to 2.0.1 has been released. ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2006q4/000246.html][{more}]]


** Announcing the winner of the logo contest (2006-12-02 19:37:04)

And the winner is: Thomas Wittek ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2006q4/000244.html][{more}]]


** GnuPG 2.0.1 released (2006-11-29 15:14:13)

We are pleased to announce the availability of GnuPG 2.0.1 ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2006q4/000242.html][{more}]]


** Dirmngr 1.0.0 released (2006-11-29 15:14:13)

We are pleased to announce the availability of Dirmngr 1.0.0 ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2006q4/000243.html][{more}]]


** GnuPG 2.0 released (2006-11-13 12:43:16)

We are pleased to announce the availability of GnuPG 2.0.0 ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2006q4/000239.html][{more}]]


** GnuPG 1.9.92 released (2006-10-11 13:43:29)

We are pleased to announce the availability of GnuPG 1.9.92 - one of the
last steps towards a 2.0 release. ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2006q4/000236.html][{more}]]


** GnuPG Logo contest (2006-09-19 14:43:08)

After 8 years the time has come to modernize the GnuPG Logo and to work
on a new layout of the website ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2006q3/000235.html][{more}]]


** Gpg4win 1.0.6 released (2006-08-29 09:52:50)

We are pleased to announce the availibility of Gpg4win, version 1.0.6
...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2006q3/000232.html][{more}]]


** Libgcrypt 1.2.3 released (2006-08-29 09:49:39)

We are pleased to announce the availability of Libgcrypt 1.2.3. Since
this is a bugfix release, it does not include any new features...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2006q3/000231.html][{more}]]


** GnuPG 1.4.5 released (2006-08-01 17:42:11)

We are pleased to announce the availability of a new stable GnuPG
release: Version 1.4.5 ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2006q3/000229.html][{more}]]


** GnuPG 1.4.4 released (2006-06-25 15:57:40)

We are pleased to announce the availability of a new stable GnuPG
release: Version 1.4.4 ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2006q2/000226.html][{more}]]


** Gpg4win 1.0.1 released (2006-04-26 13:29:58)

We are pleased to announce the availibility of Gpg4win, version 1.0.1
...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2006q2/000224.html][{more}]]


** Gpg4win released (2006-04-03 14:28:36)

After struggling for 6 month with Windows pecularities, we are finally
pleased to announce the first stable release of Gpg4win, version
1.0.0...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2006q2/000223.html][{more}]]


** GnuPG 1.4.3 released (2006-04-03 14:28:36)

We are pleased to announce the availability of a new stable GnuPG
release: Version 1.4.3 ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2006q2/000222.html][{more}]]

** GnuPG does not detect injection of unsigned data (2006-03-09 20:02:28)

In the aftermath of the false positive signature verification bug more
thorough testing of the fix has been done and another vulnerability has
been detected. This new problem affects the use of gpg for verification
of signatures which are not detached signatures. The problem also
affects verification of signatures embedded in encrypted messages; i.e.
standard use of gpg for mails. Update GnuPG as soon as possible to
version 1.4.2.2!
[[https://lists.gnupg.org/pipermail/gnupg-announce/2006q1/000216.html][{more}]]


** False positive signature verification in GnuPG (2006-02-15 12:43:54)

The Gentoo project identified a security related bug in GnuPG. When
using any current version of GnuPG for unattended signature verification
(e.g. by scripts and mail programs), false positive signature
verification of detached signatures may occur. This problem affects the
tool *gpgv*, as well as using "gpg --verify" to imitate gpgv, if only
the exit code of the process is used to decide whether a detached
signature is valid.
[[https://lists.gnupg.org/pipermail/gnupg-announce/2006q1/000211.html][{more}]]

** GnuPG 1.9.20 (S/MIME and gpg-agent) released (2005-12-20 12:56:31)

We are pleased to announce the availability of GnuPG 1.9.20 - the branch
of GnuPG featuring the S/MIME...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2005q4/000209.html][{more}]]

** Libgcrypt 1.2.2 released (2005-10-05 15:34:42)

We are pleased to announce the availability of Libgcrypt 1.2.2. Since
this is a bugfix release, it does not include any new features...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2005q4/000205.html][{more}]]


** GnuPG 1.9.19 (S/MIME and gpg-agent) released (2005-09-12 15:29:20)

We are pleased to announce the availability of GnuPG 1.9.19 - the branch
of GnuPG featuring the S/MIME...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2005q3/000204.html][{more}]]


** GnuPG Explorer Extension (GPGee) version 1.2.1 released (2005-09-08 14:41:58)

Version 1.2.1 of GPGee has now been released and is available at...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2005q3/000203.html][{more}]]


** GnuPG Explorer Extension (GPGee) version 1.2.0 released (2005-09-06 16:09:57)

Version 1.2.0 of GPGee has been released - head to the homepage at...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2005q3/000202.html][{more}]]


** GPGee version 1.1.2 - Important Security Update (2005-07-30 00:29:18)

Version 1.1.2 of GPGee has been released. This release fixes a newly
identified security issue...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2005q3/000201.html][{more}]]


** GnuPG 1.4.2 released (2005-07-27 09:53:27)

We are pleased to announce the availability of a new stable GnuPG
release: Version 1.4.2 ...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2005q3/000200.html][{more}]]


** GPGee (GnuPG Explorer Extension) version 1.1.1 (2005-07-18 04:58:16)

I have released version 1.1.1 of GPGee. This is a minor update to 1.1 to
answer a couple user...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2005q3/000199.html][{more}]]


** Second release candidate for GnuPG 1.4.2 available (2005-06-21 16:44:35
CET)

We are pleased to announce the availability of another release candidate
for the forthcoming 1.4.2 version of gnupg...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2005q2/000198.html][{more}]]


** GnuPG 1.9.17 (S/MIME and gpg-agent) released (2005-06-20 21:58:24 CET)

We are pleased to announce the availability of GnuPG 1.9.17; the
development branch of GnuPG featuring the S/MIME protocol...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2005q2/000196.html][{more}]]


** First release candidate for GnuPG 1.4.2 available (2005-05-31 14:27:33 CET)

We are pleased to announce the availability of a release candidate for
the forthcoming 1.4.2 version of gnupg...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2005q2/000195.html][{more}]]


** GnuPG 1.9.16 (S/MIME) released (2005-04-21 17:23:56 CET)

We are pleased to announce the availability of GnuPG 1.9.16; the
development branch of GnuPG featuring the S/MIME protocol...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2005q2/000194.html][{more}]]


** GnuPG 1.4.1 News (2005-03-15 17:53:36 CET)

We are pleased to announce the availability of a new stable GnuPG
release: Version 1.4.1...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2005q2/000192.html][{more}]]


** Smartcard daemon and gpg's S/MIME cousin gpgsm (2005-02-23 12:43:27 CET)

The design is different to the previous versions and we may not support
all ancient...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2005q2/000177.html][{more}]]


** Attack against OpenPGP encryption (2005-02-11 02:00:17 CET)

Last night, Serge Mister and Robert Zuccherato published a paper
reporting on an attack against OpenPGP symmetric encryption...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2005q1/000191.html][{more}]]


** Libgcrypt 1.2.1 released (2005-01-09 15:03:22 CET)

We are pleased to announce the availability of Libgcrypt 1.2.1. Since
this is a bugfix release, it does not include any new features...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2005q1/000189.html][{more}]]


** GnuPG 1.2.7 released (2004-12-28 11:54:32 CET)

As promised in the announcement of GnuPG 1.4.0, we are now pleased to
announce the availability GnuPG 1.2.7...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2004q4/000188.html][{more}]]


** Updated GnuPG 1.4.0 Windows binary (2004-12-16 22:17:10 CET)

A couple of hours ago we announced GnuPG 1.4.0, claiming that a compiled
version for MS Windows is also available. Unfortunately that Windows
version...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2004q4/000187.html][{more}]]


** GnuPG stable 1.4 released (2004-12-16 18:24:48 CET)

We are pleased to announce the availability of the new stable GnuPG
series. This first release is version 1.4.0...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2004q4/000186.html][{more}]]


** GnuPG 1.3.93 released (2004-12-14 11:06:45 CET)

The latest and hopefully last release candidate for GnuPG 1.4 is ready
for public consumption. We strongly encourage people to try this release
candidate...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2004q4/000185.html][{more}]]


** sha1sum for MS Windows released (2004-12-09 17:16:22 CET)

In the light of the recently found weaknesses in the MD5 hash function
we won't anymore accompany software announcements with MD5 checksums.
Instead SHA-1 checksums will be given...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2004q4/000184.html][{more}]]


** News available as in RSS 2.0 format (2004-11-25 22:49:58 CET)

As of today, the latest ten news from GnuPG's are available as RSS 2.0
compliant feed. Just point or paste the [[news.en.rss][RSS file]] into
your aggregator.


** GnuPG 1.3.92 released (development) (2004-10-28 14:30:58 CEST)

The latest release from the development branch of GnuPG is ready for
public consumption. This is a branch to create what will extremely soon
become the new stable release of...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2004q4/000183.html][{more}]]


** GPGME 1.0.1 released (2004-10-22 21:27:47 CEST)

We are pleased to announce version 1.0.1 of GnuPG Made Easy, a library
designed to make access to GnuPG easier for...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2004q4/000181.html][{more}]]


** GnuPG 1.3.91 released (development) (2004-10-16 14:46:21 CEST)

The latest release from the development branch of GnuPG is ready for
public consumption. This is a branch to create what will extremely soon
become the new stable release of...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2004q4/000180.html][{more}]]


** Building GnuPG for Win32 using MinGW (2004-10-12)

A new link to Carlo Luciano Bianco's page has been added under the
[[download/index][download section]] . The detailed document is
dedicated to Windows users and explains how to build GnuPG using MinGW.


** GnuPG Subkeys MiniHOWTO (2004-10-11)

With GnuPG and the possibility of having multiple subkeys, you can have
only one key, but still retain the security feature that you do not have
to revoke your primary key (and lose all signatures on it) if the key at
the office is compromised...
[[documentation/howtos.en.html#GnuPG-Subkeys][{more}]]


** GnuPG 1.3.90 released (development) (2004-10-02 15:47:23 CEST)

The latest release from the development branch of GnuPG is ready for
public consumption. This is a branch to create what will...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2004q4/000179.html][{more}]]


** GPGME 1.0.0 released (2004-09-30 18:07:54 CEST)

We are pleased to announce version 1.0.0 of GnuPG Made Easy, a library
designed to make access to GnuPG easier for...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2004q3/000178.html][{more}]]


** GnuPG 1.2.6 released (2004-08-26 12:07:34 CEST)

We are pleased to announce the availability of a new stable GnuPG
release: Version 1.2.6. The GNU Privacy Guard (GnuPG) is...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2004q3/000176.html][{more}]]


** GnuPG 1.2.5 build instruction update (2004-07-27)

Due to a problem with the gettext installation on the build machine a
little annoying bug will disturb...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2004q3/000173.html][{more}]]


** GnuPG 1.2.5 released (2004-07-27)

We are pleased to announce the availability of a new stable GnuPG
release: Version 1.2.5. The GNU Privacy Guard (GnuPG) is...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2004q3/000171.html][{more}]]


** GnuPG 1.2.5 second release candidate (2004-06-16)

We are pleased to announce the availability of the second release
candidate for GnuPG 1.2.5...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2004q2/000169.html][{more}]]


** GnuPG 1.3.6 released (development) (2004-05-22 18:07:54 CEST)

The latest release from the development branch of GnuPG is ready for
public consumption. This is a branch to create what will eventually
become GnuPG 1.4. It will change with greater frequency...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2004q2/000168.html][{more}]]


** First U.S. mirror available (2004-05-06)

We are proud to enlist on our [[download/mirrors.en.html][mirror page]]
the first mirror located in the United States of America. This is the
first tangible effort that we have logged since the rule relaxation by
the U.S. Department of Commerce about
[[http://www.crypto.com/exports/][exporting cryptography]] and we hope
that more mirrors will follow.


** Libgcrypt 1.2.0 released (2004-04-16)

We are pleased to announce the availability of Libgcrypt 1.2.0, which is
the first stable release of this general purpose crypto library...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2004q2/000167.html][{more}]]


** GnuPG 1.2.5 first release candidate (2004-03-29)

We are pleased to announce the availability of the first release
candidate for GnuPG 1.2.5...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2004q1/000166.html][{more}]]


** GnuPG 1.3.5 released (development) (2004-02-26)

The latest release from the development branch of GnuPG is ready for
public consumption. This is a branch to create what will...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2004q1/000165.html][{more}]]


** GnuPG 1.2.4 released (2003-12-24)

We are pleased to announce the availability of a new stable GnuPG
release: Version 1.2.4. The GNU Privacy Guard (GnuPG) is...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2003q4/][{more}]]


** GnuPG 1.3.4 released (development) (2003-11-27)

The latest release from the development branch of GnuPG is ready for
public consumption. This is a branch to create what will...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2003q4/][{more}]]


** GnuPG 1.2.3 patch to remove ElGamal signing keys (2003-11-27)

David Shaw wrote a patch against GnuPG 1.2.3 to disable the ability to
create signatures using the ElGamal sign+encrypt...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2003q4/][{more}]]


** GnuPG's ElGamal signing keys compromised (2003-11-27)

A severe problem with ElGamal sign+encrypt keys has been found. This
leads to a full compromise of the private key. Fortunately...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2003q4/][{more}]]


** Libgcrypt 1.1.44 released (2003-11-01)

We are pleased to announce version 1.1.44 of Libgcrypt, a general
purpose cryptography library based on...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2003q4/][{more}]]


** RISC OS port (2003-10-28)

The [[download][Download section]] now includes a link to Stefan
Bellon's page who ported GnuPG to the RISC OS platform.


** GPA 0.7.0 released (2003-10-22)

We are pleased to announce the release of GPA 0.7.0. GPA is a graphical
frontend for the GNU Privacy Guard...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2003q4/][{more}]]


** GnuPG 1.3.3 released (development) (2003-10-10)

The latest release from the development branch of GnuPG is ready for
public consumption. This is a branch...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2003q4/][{more}]]


** HTTP access to FTP server dismissed (2003-09-22)

Because the HTTP protocol has a couple of problems compared to FTP when
transmitting large files, we decided to dismiss this service for our
server. All the files are thus only available from
[[ftp://ftp.gnupg.org/]] via FTP.


** A Practical Introduction to GPG in Windows (2003-08-22)

The documentation section now contains a
[[documentation/guides.en.html#GPG-Win][new guide]] from Brendan Kidwell
which will hopefully help out Windows users who couldn't get the thing
to work.


** GnuPG one-two-three released (2003-08-22)

We are pleased to announce the availability of a new stable GnuPG
release: Version 1.2.3...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2003q3/][{more}]]


** Libgcrypt 1.1.42 released (2003-07-31)

We are pleased to announce version 1.1.42 of Libgcrypt, a general
purpose cryptography library...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2003q3/][{more}]]


** GnuPG 1.2.3 second release candidate (2003-07-30)

We are pleased to announce the availability of the second release
candidate for GnuPG 1.2.3...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2003q3/][{more}]]


** OpenPGP Smartcards (2003-07-07)

The new OpenPGP smartcards for GnuPG will be shown the first time at the
[[http://www.linuxtag.de/2003/en/index.html][LinuxTag]] , Europe's
largest GNU/Linux exhibition (booth G24).


** GnuPG Keysigning Party HOWTO (2003-06-16)

Documentation section can now count a new entry among its HOWTOs. It is
a valuable source of information for understanding and organizing a
[[documentation/howtos.en.html#GnuPG-Keysigning-Party][GnuPG keysigning party]] .


** GnuPG 1.3.2 released (2003-05-27)

The latest release from the development branch of GnuPG is ready for
public consumption. The more GnuPG-familiar user is encouraged try this
release...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2003q2/000153.html][{more}]]


** Key validity bug in GnuPG 1.2.1 and earlier (2003-05-04)

As part of the development of GnuPG 1.2.2, a bug was discovered in the
key validation code. This bug causes keys with more than one user ID...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2003q2/][{more}]]


** GnuPG 1.2.2 released (2003-05-03)

We are pleased to announce the availability of a new stable GnuPG
release: Version 1.2.2...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2003q2/][{more}]]


** GnuPG.org/(it) 1.0 (2003-04-23)

Version 1.0 of this site's Italian translation has been released. - È
stata rilasciata la versione 1.0 della traduzione italiana di questo
sito.


** New revision of GPH French translation (2003-04-17)

Thanks to Jean-francois for the new French revision of
[[documentation/guides.en.html#gph][The GNU Privacy Handbook]] .


** The No-War banner (2003-04-08)

Recently, a no-war banner has been added to the site. Because not all of
us at GnuPG.org agreed on it, we moved it to the bottom of the page. We
invite you to read more on our mailing-list.
[[https://lists.gnupg.org/pipermail/gpgweb-devel/2003q1/][{more}]]


** GnuPG.org/(es) 0.9 (2003-02-19)

Ha visto la luz la versión 0.9 de la traducción al castellano de este
sitio. - Version 0.9 of this site spanish translation has been released.


** GPA 0.6.1 released (2003-02-03)

We are pleased to announce the release of GPA 0.6.1
[[https://lists.gnupg.org/pipermail/gnupg-announce/2003q1/][{more}]]


** Libgcrypt 1.1.12 released (2003-01-20)

I am pleased to announce a new Beta version of Libgcrypt, GNU's
implementation of basic crypto functions. Libgcrypt is a general...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2003q1/][{more}]]


** GPA 0.6.0 released (2002-12-24)

We are pleased to announce the release of GPA 0.6.0. GPA is a graphical
frontend for the GNU Privacy Guard...
[[gpa-dev/2002-December/index][{more}]]


** GnuPG signature key update and X-Request-PGP (2002-12-23)

The key used to sign GnuPG distributions would expire in a few days. I
have extended the lifetime of this key for another...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2002q4/][{more}]]


** GPGME 0.4.0 released (2002-12-23)

We are pleased to announce version 0.4.0 of GnuPG Made Easy, a library
designed to make access to GnuPG easier for...
[[gpa-dev/2002-December/index][{more}]]


** Libgcrypt 1.1.11 released (2002-12-22)

I am pleased to announce the availability of libgcrypt version 1.1.11.
Libgcrypt is a general purpose cryptographic library based on the code
from GnuPG and...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2002q4/][{more}]]


** gnupg.org 1.1 released (2002-12-15)

New site look has gained several positive critical comments since
revision 1.0 was out, but many bugs were also reported. This revision
tries to fix the most part of them.



** cryptplug 0.3.15 released (2002-12-05)

Due to an error in the configuration system, the previous release had
some problems. This has been fixed and a new version...
[[gpa-dev/2002-December/index][{more}]]


** newpg 0.9.4 released (2002-12-04)

I have just released newpg 0.9.4. NewPG is the S/MIME variant of GnuPG
which does also include the gpg-agent, useful even for...
[[gpa-dev/2002-December/index][{more}]]


** cryptplug 0.3.14 released (2002-12-04)

We have just released the first standalone version of cryptplug.
cryptplug is required for GnuPG and S/MIME support under KDE...
[[gpa-dev/2002-December/index][{more}]]


** gpgme 0.3.14 released (2002-12-04)

We have released gpgme 0.3.14. This version fixes a segv and a race
condition with locales. gpgmeplug is not anymore included...
[[gpa-dev/2002-December/index][{more}]]


** New look-and-feel site released to the public (2002-12-01)

After about four months of WML coding (well, summer was on the way ;-),
first revision of the new site look-and-feel was released today. Site is
available in english only for now.


** OpenCDK 0.3.3 (2002-11-25)

This is the first public announcement for OpenCDK. It is a library to
provide some basic parts of the OpenPGP Message Format...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2002q4/][{more}]]


** Pyme -- Python OO interface to GPGME (2002-11-20)

Today I am announcing the first release of Pyme, the brand-new Python
bindings for GPGME....
[[https://lists.gnupg.org/pipermail/gnupg-announce/2002q4/][{more}]]


** GnuPG 1.3.1 released (development) (2002-11-12)

The latest release from the development branch of GnuPG is ready for
public consumption. This is a branch to create what will...


** GPGRemail v0.1 initial announcement (2002-11-06)

GPGRemail is a minimalistic mailinglist software, meant for small,
private, mailinglists that require strong cryptography via...


** RPMs (2002-10-28)

I'm currently uploading RPMs packages for gnupg 1.2.1. At this moment
I've uploaded src and mdk 9.0 packages. The latter...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2002q4/][{more}]]


** GnuPG 1.2.1 Windows update released (2002-10-26)

Due to a bug in the recent mingw32/cpd toolkit the latest GnuPG binary
for Windows did not work on Windows NT. I have build...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2002q4/][{more}]]


** GnuPG 1.2.1 has been released (2002-10-25)

Please see this [[download/release_notes.en.html#news-2002-10-25][list
of changes]] and then go to the [[download/index.en.html][download
instructions]] .


** GnuPG 1.3.0 released (development) (2002-10-18)

The first release from the new development branch of GnuPG is ready for
public consumption. This is a branch to create what...
[[https://lists.gnupg.org/pipermail/gnupg-announce/2002q4/][{more}]]


** GnuPG 1.2.0 released (2002-09-21)

Far too many enhancements to be listed here, please see the
[[https://lists.gnupg.org/pipermail/gnupg-announce/2002q3/000252.html][announcement mail]] .


** New site (2002-06-20)

Developmenent of the site new look and feel has started.


** ftp.gnupg.org HTTP access (2002-05-08)

[[http://ftp.gnupg.org][ftp.gnupg.org]] can now also be accessed by
HTTP.


** GnuPG 1.0.7 released (2002-04-29)

Far too many enhancements to be listed here, please see the
[[https://lists.gnupg.org/pipermail/gnupg-announce/2002q2/000251.html][announcement mail]] .


** GPA 0.4.3 released (2002-01-14)

[[software/gpa/index.en.html][GPA]] 0.4.3 has been released.


** GPA pages (2001-11-15)

[[software/gpa/index.en.html][GPA pages]] reflect latest released version (gpa-0.4.2) now.


** GnuPG 1.0.6 released (2001-05-29)

See the [[download/release_notes.en.html#news-2001-05-29][release note]].


** GnuPG 1.0.5 for W32 released (2001-05-02)

Released GnuPG 1.0.5 binary for W32.

** GnuPG 1.0.5 released (2001-04-29)

-  The semantics of --verify have changed.
-  Corrected hash calculation for input data larger than 512M.
-  Large File Support is now working.
-  A bunch of new options and commands.
-  Keyserver support for the W32 version.
-  Better handling of key expiration and subkeys.
-  Estonian and Turkish translation.
-  The usual fixes and other enhancements.


** New CVS access instructions (2001-04-18)

Changed the instructions for CVS access and add a list of available
modules.


** GnuPG Tools (2001-04-03)

Add a new webpage about GnuPG tools.


** News about gnupg.de (2001-03-28)

News flash about [[http://www.gnupg.de][www.gnupg.de]] .


** Link to Phil Zimmermann (2001-03-24)

Add a link to [[http://web.mit.edu/~prz][Phil Zimmermann]] 's homepage.


** New page about GPGME (2001-02-22)

Add a page about [[software/gpgme/index.en.html][GPGME]] .


** Patch for GnuPG 1.0.4 released (2000-11-30)

Fixed a serious bug which could lead to false positives when checking
detached signatures.


** New web design (2000-10-26)

New design of these web pages.


** GnuPG 1.0.4 W32 released (2000-10-23)

Pre-compiled version of [[download/index.en.html][GnuPG 1.0.4]] for
Windows released.


** GnuPG 1.0.4 (2000-10-17)

-  Fixed a serious bug which could lead to false signature verification
   results when more than one signature is fed to gpg.
-  New utility gpgv which is a stripped down version of gpg to be used
   to verify signatures against a list of trusted keys.
-  Rijndael (AES) is now supported.


** German GPH (2000-10-06)

Put the [[documentation/guides.en.html#gph][German version]] of the GPH
online.


** Secure Telephony (2000-09-27)

Add a link about secure telephony and a pointer to a Japanese
translation of RFC2440.


** GnuPG 1.0.3 released (2000-09-20)

-  RSA support.
-  Supports the new MDC encryption packet.
-  Default options changed for better compatibility with PGP 7.
-  The usual fixes and other enhancements.


** FAQ (2000-09-06)

Add a [[documentation/faqs.en.html][FAQ]] .


** Site improvements (2000-08-28)

Add a short menu to the top of the docs page. Add a note about the PGP
ARR problem.


** Links to GPH (2000-08-08)

Put links to the GPH into the doc webpage.


** Italian web site (2000-08-02)

Italian translation of the web pages.


** GnuPG 1.0.2 released (2000-07-12)

A lot of fixes and enhancements.


** Pages about PGA (2000-06-29)

Add some pages about the [[software/gpa/][GPA]].


** Two new supported OSes (2000-03-20)

Add 2 OSes to the list of supported systems.


** CVS access (2000-03-15)

[[https://cvs.gnupg.org/][cvs.gnupg.org]] provides browsable access to
the CVS tree of GnuPG and related projects.


** GnuPG 1.0.1 released (1999-12-16)

Bug fixes and small enhancements.


** GnuPG 1.0.0 released (1999-09-07)

Released the first production version.


** GnuPG 0.9.11 released (1999-09-03)

Some more fixes and cleanups.


** GnuPG 0.9.10 released (1999-08-04)

Minor bug fixes.


** GnuPG 0.9.9 released (1999-07-23)

-  Yet another chunk of options.
-  More bug fixes.


** GnuPG 0.9.8 released (1999-06-26)

-  A couple of new options.
-  Yet another workaround for PGP2.
-  Other bug fixes.


** GnuPG 0.9.7 released (1999-05-23)

-  Workarounds for a couple of PGP2 bugs.
-  Other bug fixes.


** GnuPG 0.9.6 released (1999-05-06)

-  Bug fixes.
-  Subkey and signature revocations.


** GnuPG 0.9.5 released (1999-03-20)

-  Bug fixes.
-  --recv-keys command

** GnuPG 0.9.4 released (1999-03-08)

Bug fixes.


** GnuPG 0.9.3 released (1999-02-19)

-  Bug fixes.
-  Some new options.


** GnuPG 0.9.2 released (1999-01-20)

-  Bug fixes.
-  HKP keyserver support.

** GnuPG 0.9.1 released (1999-01-01)

-  Fixed some serious bugs.
-  Some internal redesign.
-  Polish language support.
-  Setup a anonymous rsync server.



** GnuPG 0.9.0 released (1998-12-23)

-  Option to dash-escape "From" in clear text messages.
-  Better support for unices without /dev/random.
-  Fixed some bugs.


** GnuPG 0.4.5 released (1998-12-08)

-  Brazilian translation.
-  Improved key import.
-  Loadable random gathering stuff.
-  Files are now locked during updates.


** GnuPG 0.4.4 released (1998-11-20)

-  Spanish translation.
-  Fixed the way expiration dates are stored.
-  Key validation is now much faster and some more bugs fixed.
-  New feature to support signed patch files.


** GnuPG 0.4.3 released (1998-11-08)

-  Russian translation.
-  Now lists all matching names.
-  Experimental support for keyrings store in GDBM files.
-  Many bug fixes.


** GnuPG 0.4.1 released (1998-10-07)

-  Fixed a couple of bugs and add some more features.
-  Checked OpenPGP compliance.
-  PGP 5 passphrase are now working.


** GnuPG 0.4.0 released (1998-09-18)

-  Fixed a serious Bug in 0.3.5.
-  Added 3DES.


** GnuPG 0.3.5 released (1998-09-14)

-  Do not use this version!
-  Anonymous enciphered messages.
-  Building in another directory now work better.
-  Blowfish weak key detection mechanism.


** GnuPG 0.3.4 released (1998-08-11)

Relased revision 0.3.4.


** GnuPG 0.3.3 released (1998-08-08)

-  Alternate user IDs.
-  A menu to sign, add, remove user ids and other tasks.
-  [[http://www.counterpane.com/twofish.html][Twofish]] as a new experimental cipher algorithm.
-  Ability to run as a coprocess; this is nice for frontends.


** GnuPG 0.3.2 released (1998-07-09)

Bug fixes.


** GnuPG 0.3.1 released (1998-07-06)

-  Bug fixes.
-  More in compliance with OpenPGP.


** GnuPG 0.3.0 released (1998-06-25)

-  Major enhancements.
-  More complete v4 key support: Preferences and expiration time is set
   into the self signature.
-  Key generation defaults to DSA/ElGamal keys, so that new keys are
   interoperable with pgp5.
-  Support for dynamic loading of new algorithms.



** GnuPG 0.2.19 released (1998-05-29)

-  Tiger has now the OpenPGP assigned number 6. Because the OID has
   changed, old signatures using this algorithm can't be verified.
-  GnuPG now encrypts the compressed packed and not any longer in the
   reverse order; anyway it can decrypt both versions.
-  =--add-key= works and you are now able to generate subkeys.
-  It is now possible to generate ElGamal keys in v4 packets to create
   valid OpenPGP keys.
-  Some new features for better integration into MUAs.


** GnuPG 0.2.18 released (1998-05-15)

-  Add key generation for DSA and v4 signatures.
-  Fixed a small bug in the key generation.
-  New option =--compress-algo 1= to allow the creation of compressed
   messages which are readable by PGP.


** GnuPG 0.2.17 released (1998-05-04)

-  More stuff for OpenPGP: Blowfish is now type 20, comment packets
   moved to a private type, packet type 3 now prepends conventional
   encryption packets.
-  Fixed a passphrase bug and some others.



** GnuPG 0.2.16 released (1998-04-28)

-  Experimental support for TIGER/192.
-  Standard cipher is now Blowfish with 128 bit key in OpenPGP's CFB
   mode.


** GnuPG 0.2.15 released (1998-04-09)

-  Fixed a bug with the old checksum calculation for secret keys.
-  CAST5 works (using PGP's strange CFB mode).

** GnuPG 0.0.0 released (1997-12-20)

First release.
