#+TITLE: GnuPG - Privacy Policy
#+STARTUP: showall indent
#+SETUPFILE: "share/setup.inc"

* Privacy Policy
#+index: privacy policy
#+index: analytics
#+index: log files

** Log files

This website uses log files to identify problems with the site and to
monitor traffic.  The raw log files are kept for a week and are then
deleted.  For web analytics the data from the log files is anonymized
by truncating the IP addresses to 40 bit for IPv6 and 20 bits for IPv4
and send to another machine.  Neither the raw log files nor the
anonymized data from the log file is shared with anyone; however
system administrators have access to the log files to solve technical
problems.  Reports on the use of this site will always be fully
anonymized and may eventually be published at this site.

We have not been forced by any court order or other means not to obey
to the above rules.

** History

- 2013-11-07 :: Installed Piwik web analytics software and wrote a
                privacy policy.

- 2014-03-12 :: Removed the Piwik web analytics software and changed
                the policy to allow for log file based analytics.
